[8.0][IMP] Transfer the Gross Profit fields to the Deliverable lines
OCA/business-requirement pull request #105
Opened 2017-04-01 09:19 UTC by sudhir-serpentcs

Transfer the Gross Profit fields to the Deliverable lines.

BR with BRD_cost give the calculation for Total Revenue-Total Cost = Gross Profit
Need to have on every DL the same calculation based on their own RL
So DL 1 will have a partial Total Revenue DL 1 - Total Cost DL 1 = Gross Profit DL 1

@elicoidal

2017-04-02 02:54 UTC, elicoidal requested changes
Please review the logic.
Please review the form fields to be added
Please review the ACL.

2017-04-02 02:54 UTC, elicoidal commented on business_requirement_deliverable_cost/models/business.py
> +    @api.depends('resource_ids.price_total',
I am not sure this does what I am expecting.
Here is what I need: DL.gross_profit = DL.price_total - sum(RL.cost)
It should be updated whenever the RL.cost or DL.price_total changes.

Can you double check? @sudhir-serpentcs

2017-04-02 02:54 UTC, elicoidal commented on business_requirement_deliverable_cost/views/business.xml
> +                    <field name="gross_profit"/>
Not only: I would like to see the same fields as in the BR (check screenshot that I have provided).
Besides it should only be visible to the "cost" group

2017-04-03 06:03 UTC, sudhir-serpentcs commented
@elicoidal  
Changed calculation for gross profit and added ACL.
https://github.com/OCA/business-requirement/pull/105/commits/a59e162ee32249967115198f7003980f14f06225

2017-04-03 09:12 UTC, elicoidal commented
@sudhir-serpentcs please check this and the screenshot. The current code doesnot cover it all AFAIK.

2017-04-08 01:28 UTC, elicoidal commented
please follow: https://github.com/OCA/business-requirement/issues/84

2017-04-11 06:40 UTC, sudhir-serpentcs commented
@elicoidal @victormartinelicocorp 
can you please review code.

2017-04-11 10:22 UTC, elicoidal approved these changes
Functional tests are OK

2017-04-12 06:29 UTC, elicoidal commented
Will need to be fixed when #113 is finished

2017-04-16 00:54 UTC, elicoidal commented
@sudhir-serpentcs can you rebase your work to fit the changes made in #113

2017-04-18 01:11 UTC, elicoidal commented
@sudhir-serpentcs once you fix the link to #113 we could quickly merge

2017-04-20 01:39 UTC, elicoidal commented
@sudhir-serpentcs #113 is fixed. Can you rebase and fix this one?

2017-04-24 05:32 UTC, sudhir-serpentcs commented
@elicoidal 
please review code.

2017-04-24 06:22 UTC, elicoidal commented
@sudhir-serpentcs I have lost the description field in deliverable

2017-04-24 11:47 UTC, sudhir-serpentcs commented
@elicoidal 
Added Description field, please review code.

2017-04-24 21:04 UTC, elicoidal commented
@sudhir-serpentcs far from been ready: can you retest the full process?

When creating a RL in the DL, I have following js error: Error: NameError: name 'business_requirement_id' is not defined

2017-04-25 07:29 UTC, sudhir-serpentcs commented
@elicoidal  
Improved code as per comment.
please review code

2017-04-25 08:16 UTC, elicoidal commented
@sudhir-serpentcs thanks it works now.
I want to change the position of the fields as it is a bit weird as is (so you will have probably to update both modules).

First column:
* Business Requirement
* Product
* Name

Second column:
* Quantity 
* Sales Price
* Currency
* Total revenue
* Total procurement
* Total tasks
* Estimated Gross Profit

2017-04-25 10:06 UTC, sudhir-serpentcs commented
@elicoidal 
changed the position of the fields.
please review code.

2017-04-26 01:44 UTC, elicoidal commented
@sudhir-serpentcs Position of the fields is correct in DL form. Thanks!

I have the following small improvements:
* Total revenue+currency should appear in BR tree view and total at bottom (#108). Should appear in pivot view.
* RL contains price/cost info but not when they are in DL
* Currency is not set if no customer/pricelist is select. It should be the company currency by default.
* Responsible is not in the BR tree View. It should be the first
* Remove "Created on" in the BR Tree view
* the smart button Deliverable Lines should add the total revenue between parenthesis. Rename Deliverable Lines => Deliverable
* the smart button Resource Lines should add the total cost between parenthesis. Rename Resources Lines => Resources

2017-04-26 10:55 UTC, sudhir-serpentcs commented
@elicoidal 
Changed code as per comment.
please review code.

2017-04-27 01:55 UTC, elicoidal commented
@sudhir-serpentcs almost there. A couple of details left:
- [ ] RL contains Sales price/Revenue info but not when they are in DL (my previous comment was not clear)
- [ ] add the currency in tab Cost control in BR, same as in deliverable.
- [ ] In BR pivot: I dont have the Total revenue, Total Cost and Gross profit as measure
- [ ] In deliverable pivot: I dont have the Total revenue, Total Cost and Gross profit as measure
- [ ] In resource pivot: I dont have the Total revenue and Total Cost as measure (While they appear in the table)

Rest looks awesome!

2017-04-27 07:10 UTC, sudhir-serpentcs commented
@elicoidal 
Improved pivot views & code as per comments.
please review code.

2017-04-27 09:21 UTC, elicoidal commented
@sudhir-serpentcs still not there (check: https://github.com/OCA/business-requirement/pull/105#issuecomment-297589631):
- [ ] DL and BR pivot are not complete. 
- [ ] BR pivot should be table by default and is broken. Not all measure are available
- [ ] DL Pivot: I miss cost fields (unit price and total)

2017-04-27 12:09 UTC, sudhir-serpentcs commented
@elicoidal 

>DL Pivot: I miss cost fields (unit price and total)

Changed code as per comments, except the above point as I could not find the mentioned fields.

Please review code.

2017-04-27 12:39 UTC, dreispt reviewed
LGTM, but a few nitpicks to address

2017-04-27 12:39 UTC, dreispt commented on business_requirement/views/business_view.xml
> +                    <field name="responsible_id"/>
Missing one indentation space

2017-04-27 12:39 UTC, dreispt commented on business_requirement/views/business_view.xml
> +                        <filter string="Responsible" icon="terp-go-home" context="{'group_by':'responsible_id'}"/>
Icons are deprecated afaik

2017-04-27 12:39 UTC, dreispt commented on business_requirement_deliverable/models/business.py
> +        compute='_compute_get_currency'
No problem with leaving the trailing comma here

2017-04-27 12:39 UTC, dreispt commented on business_requirement_deliverable/models/business.py
> +                brd.currency_id = self.env.user.company_id.currency_id.id
Afaict you should remove the trailing `.id`: you want to reference the Currency record, and not it's numeric id.

2017-04-27 12:39 UTC, dreispt commented on business_requirement_deliverable/tests/test_br.py
> +        self.br._compute_rl_total_cost()
You're not actually testing the code here.
You should add lines to a BR, and then read the totals and compare with the expected value...

2017-04-27 12:39 UTC, dreispt commented on business_requirement_deliverable_cost/models/business.py
> +                        'price_total'))
The indentation was correct.

2017-04-27 12:39 UTC, dreispt commented on business_requirement_deliverable_cost/models/business.py
> +                        'price_total'))
Don't remove the indentation.

2017-04-27 12:50 UTC, elicoidal commented
Pivot view is working :+1: 

> DL Pivot: I miss cost fields (unit price and total)
Changed code as per comments, except the above point as I could not find the mentioned fields.

You are right they must be function (maybe make them storable in both BR and DL): Total procurement / Total tasks

2017-04-27 12:50 UTC, elicoidal commented
thanks @dreispt for your review

2017-04-28 07:31 UTC, sudhir-serpentcs commented
@dreispt Have made the requested changes.

@elicoidal And have added Total procurement / Total tasks to the pivot view, yes had to make it storable.

2017-04-28 07:48 UTC, dreispt approved these changes
LGTM. Thanks for the patience.

2017-04-28 08:11 UTC, elicoidal commented
LGTM too! merging

2017-04-28 08:11 UTC, merged