[8.0][WIP] Added Earned Value Management Report
OCA/business-requirement pull request #107
Opened 2017-04-05 03:52 UTC by sudhir-serpentcs

@elicoidal   Added Earned Value Management Report.

2017-04-05 04:03 UTC, elicoidal requested changes
Some remarks.
Besides, to be tested.

2017-04-05 04:03 UTC, elicoidal commented on business_requirement_earned_value/report/br_earned_value_report.py
> +            CREATE VIEW business_requirement_earned_value_report AS (
I see a lot of div by zero potential issues in the current view.

2017-04-05 04:03 UTC, elicoidal commented on business_requirement_deliverable_cost/models/business.py
> -                            'price_total'))
irrelevant

2017-04-05 04:03 UTC, elicoidal commented on business_requirement_earned_value/report/__init__.py
> +# © 2016 Elico Corp (www.elico-corp.com).
2017 (everywhere)

2017-04-05 13:14 UTC, sudhir-serpentcs commented
@elicoidal 
Please review code.

2017-04-05 22:12 UTC, elicoidal requested changes
Almost there!

2017-04-05 22:12 UTC, elicoidal commented on business_requirement_earned_value/report/br_earned_value_report_view.xml
> +        <menuitem action="action_earned_value_report" id="menu_action_deliverable_report"
This report should only visible to the cost group

2017-04-05 22:33 UTC, elicoidal commented
almost there!

2017-04-05 22:33 UTC, elicoidal commented
please check Travis and Runbot as well

2017-04-06 06:01 UTC, martintorresvm requested changes
Please have a check and amend if necessary

2017-04-06 06:01 UTC, victormartinelicocorp commented on business_requirement_earned_value/report/br_earned_value_report.py
> +    hr_timesheet_product =\
@sudhir-serpentcs layout is not ok.
as example do as here:
hr_timesheet_product = fields.Many2one(
    'product.product',
    'HR Timesheet Product',
    ...,)

And amend for the others fields as well

2017-04-06 06:01 UTC, victormartinelicocorp commented on business_requirement_earned_value/report/br_earned_value_report.py
> +            CASE WHEN (pt.effective_hours + pt.remaining_hours) > 0 THEN
@sudhir-serpentcs if 
`pt.effective_hours = 0`
`pt.remaining_hours = 2`

condition `(pt.effective_hours + pt.remaining_hours) > 0` is true then a division 0/2 on Postgress will cause error, don't you think?

2017-04-06 07:38 UTC, YogeshMahera-SerpentCS commented on business_requirement_earned_value/report/br_earned_value_report.py
> +            CASE WHEN (pt.effective_hours + pt.remaining_hours) > 0 THEN
@victormartinelicocorp 

no if 0/2
condition should be (pt.remaining_hours) > 0

2017-04-06 07:40 UTC, YogeshMahera-SerpentCS commented on business_requirement_earned_value/report/br_earned_value_report.py
> +            CASE WHEN (pt.effective_hours + pt.remaining_hours) > 0 THEN
@victormartinelicocorp 

no if 0/2
condition should be (pt.remaining_hours) > 0

2017-04-06 08:02 UTC, victormartinelicocorp commented on business_requirement_earned_value/report/br_earned_value_report.py
> +            CASE WHEN (pt.effective_hours + pt.remaining_hours) > 0 THEN
Yes, please amend

2017-04-06 12:29 UTC, sudhir-serpentcs commented
@elicoidal @victormartinelicocorp 
Added group and Improved code.
please review code.

2017-04-07 00:34 UTC, elicoidal commented on business_requirement_earned_value/report/br_earned_value_report_view.xml
> +            parent="base.menu_project_report" groups="business_requirement_deliverable_cost.group_business_requirement_cost_control"/>
Please improve formatting (one attribute one line)

2017-04-07 00:35 UTC, elicoidal commented on business_requirement_earned_value/__openerp__.py
> +    'summary': 'Manage the Business Requirement Deliverables and \
BI report for the based on Earned Value Management

2017-04-07 00:37 UTC, elicoidal requested changes
Please add a README file (based on business_requirement module) so that I can create the content

2017-04-07 07:17 UTC, nikul-serpentcs commented
@elicoidal @victormartinelicocorp 

Added README.rst  and Improved code.

2017-04-07 09:13 UTC, sudhir-serpentcs commented
@elicoidal @victormartinelicocorp 

Added README.rst  and Improved code.

2017-04-09 04:42 UTC, elicoidal approved these changes

2017-04-09 11:51 UTC, elicoidal commented
I made some functional tests and I have several feedbacks.

1. I cannot relate the report result with the set up I did in the BR.
Here are the DL/RL (101 in total)
![screenshot from 2017-04-09 19-28-43](https://cloud.githubusercontent.com/assets/7600613/24836955/780c214e-1d5b-11e7-807b-26d7dd064e4b.png)
![screenshot from 2017-04-09 19-28-32](https://cloud.githubusercontent.com/assets/7600613/24836952/71605cd4-1d5b-11e7-80c1-b5caa7deda35.png)

Here are the timesheets I have inputed:
![screenshot from 2017-04-09 19-27-03](https://cloud.githubusercontent.com/assets/7600613/24836953/72611ba0-1d5b-11e7-83e2-7146cd96157b.png)

Here is the result:

I would have expected: 
* Planned Hours: 101 instead of 404
* Product cost: 25.099 (is a calculation as we cannot get actual cost for multiple lines: cost/hours)
* Cost: 2535 instead of 10140
* Actual time: 60 instead of 240
* Product cost from TS: 30 instead 600 (could be calculation: Actual cost / Actual time)
* Actual Cost: 60x30= 1800 instead of 18000
(rest of column are obviously calculated).

2. Besides can you change the following column string:
* Planned Time in RL: Planned Time
* Product Cost in RL: Plan. Unit Cost
* Actual Time in Timesheet => Actual Time
* Product Cost from Timesheet Product => Act. Unit Cost

3. Other remarks
* If there is no timesheet, the report is empty: it should display the BR content with actual time = 0
* Name: should be BR name+description

2017-04-09 11:52 UTC, elicoidal requested changes
Failed functional tests

2017-04-12 04:27 UTC, sudhir-serpentcs commented
@elicoidal @victormartinelicocorp 
please review code.

2017-04-13 01:14 UTC, elicoidal commented
@sudhir-serpentcs 
Retested and still not correct (although seems improving: now it is double instead of quadruple...).
![screenshot from 2017-04-13 09-12-14](https://cloud.githubusercontent.com/assets/7600613/24985874/8a338d00-2029-11e7-806d-5edf45324308.png)

Please check the test I have written in https://github.com/OCA/business-requirement/pull/107#issuecomment-292781110 before submitting for review.

2017-04-13 07:48 UTC, sudhir-serpentcs commented
@elicoidal @victormartinelicocorp 

please review code

2017-04-14 02:23 UTC, elicoidal commented
@sudhir-serpentcs it is better. Some additional feedback:
- [ ] Please update the titles as in https://github.com/OCA/business-requirement/pull/107#issuecomment-292781110
- [ ] Project completion should appear as 81 not 0.81 (like % variance)
- [ ] Variance should be reversed (negative)
- [ ] Earned Value column seems incorrect

2017-04-14 08:58 UTC, sudhir-serpentcs commented
@elicoidal @victormartinelicocorp

please review code

2017-04-14 11:00 UTC, elicoidal commented
For https://github.com/OCA/business-requirement/pull/107#issuecomment-294069860 all is clear!
Small details I want to adjust:
* Total expected time => Total Exp. time
* % Project Completion => % Completion
After that, good to merge :)

2017-04-14 11:34 UTC, sudhir-serpentcs commented
@elicoidal @victormartinelicocorp

please review code

2017-04-14 23:00 UTC, elicoidal commented
Good job! @sudhir-serpentcs

2017-04-14 23:00 UTC, elicoidal approved these changes

2017-04-14 23:01 UTC, elicoidal commented
@seb-elico @victormartinelicocorp can you review?

2017-04-16 00:51 UTC, elicoidal commented
@pedrobaeza @dreispt @seb-elico @victormartinelicocorp Let's move forward?

2017-04-17 07:35 UTC, pedrobaeza approved these changes

2017-04-17 07:35 UTC, pedrobaeza commented on business_requirement_deliverable_cost/models/business.py
> -                            'price_total'))
Don't make this change in the PR.

2017-04-17 09:11 UTC, sudhir-serpentcs commented
@pedrobaeza @elicoidal 

please review code

2017-04-17 09:17 UTC, pedrobaeza approved these changes

2017-04-17 09:17 UTC, merged