Franksongfeng 8.0 fix business requirement deliverable project categ
OCA/business-requirement pull request #109
Opened 2017-04-07 05:28 UTC by victormartinelicocorp

To continue work done on #59

2017-04-07 05:29 UTC, victormartinelicocorp commented
@elicoidal I would suggest close #59 as it will continue or this PR.

2017-04-07 06:22 UTC, victormartinelicocorp commented
All test has passed. Please review @elicoidal @seb-elico

2017-04-07 07:14 UTC, seb-elico requested changes

2017-04-07 07:14 UTC, seb-elico commented on business_requirement_deliverable_project_categ/README.rst
> +* Eric Caudal<eric.caudal@elico-corp.com>
@victormartinelicocorp there's no space between name and email, Travis doesn't check this?

2017-04-07 07:21 UTC, victormartinelicocorp commented on business_requirement_deliverable_project_categ/README.rst
> +* Eric Caudal<eric.caudal@elico-corp.com>
Me neither, if Travis could check format of rst files never face before. But indeed I need to fix it

@gurneyalex Could you help us with this question?

2017-04-09 00:38 UTC, elicoidal approved these changes

2017-04-09 02:09 UTC, elicoidal commented
@seb-elico please recheck

2017-04-10 05:18 UTC, victormartinelicocorp commented
@elicoidal @seb-elico we actually are using this module included I just fix Frank's code so could be possible merged and switch to OCA. 

Please let me know if we could move forward.

2017-04-10 05:36 UTC, elicoidal commented
@victormartinelicocorp OK for me.
The module will be merged soon in OCA anyway

2017-04-10 06:01 UTC, seb-elico approved these changes

2017-04-10 06:02 UTC, seb-elico commented
@elicoidal @victormartinelicocorp All good on my side. Runbot cover decreased of 0.3%, I don't know if it's a blocking point

2017-04-10 06:07 UTC, victormartinelicocorp commented
> @elicoidal @victormartinelicocorp All good on my side. Runbot cover decreased of 0.3%, I don't know if it's a blocking point

@seb-elico  `Coveralls` is a little deficient on giving good analysis but if you check the message on `covecov/project` then you'll see that for this PR is normal.

`Absolute coverage decreased by -0.25% but relative coverage increased by +6.19%`

2017-04-16 00:52 UTC, elicoidal commented
@pedrobaeza @dreispt @seb-elico Let's move forward?

2017-04-17 07:32 UTC, pedrobaeza approved these changes

2017-04-17 07:32 UTC, merged