[FIX] business_requirement
OCA/business-requirement pull request #116
Opened 2017-04-13 10:24 UTC by victormartinelicocorp

To fix https://github.com/OCA/business-requirement/issues/114

2017-04-13 10:24 UTC, victormartinelicocorp commented
@elicoidal @seb-elico

cc @sudhir-serpentcs

2017-04-14 01:15 UTC, elicoidal approved these changes

2017-04-16 00:50 UTC, elicoidal commented
@pedrobaeza @dreispt @seb-elico Let's move forward?

2017-04-17 07:49 UTC, pedrobaeza requested changes

2017-04-17 07:49 UTC, pedrobaeza commented on business_requirement/models/business.py
> -                formatted_name = '[{}] {}'.format(br.ref, br.description)
The solution is to put:
```
formatted_name = u'[{}] {}'.format(br.ref, br.description)
```
not to make the other change

2017-04-17 12:09 UTC, victormartinelicocorp commented on business_requirement/models/business.py
> -                formatted_name = '[{}] {}'.format(br.ref, br.description)
Sure, thanks for review!

2017-04-19 11:36 UTC, victormartinelicocorp commented on business_requirement/models/business.py
> -                formatted_name = '[{}] {}'.format(br.ref, br.description)
done

2017-04-20 01:10 UTC, elicoidal commented
@pedrobaeza your comment is attended so I move forward :)

2017-04-20 01:10 UTC, merged