[RM] business_requirement_deliverable_cost
OCA/business-requirement pull request #118
Opened 2017-04-14 04:51 UTC by victormartinelicocorp

Remove pricelist from project
Calculation of product sales prices only is linked to the customer
or default value on product

2017-04-14 04:52 UTC, victormartinelicocorp commented
Once #117 is merged and this one as well next step is to calculate pricelist with new estimation field.

@elicoidal @seb-elico

2017-04-14 05:58 UTC, elicoidal approved these changes
FT

2017-04-14 05:58 UTC, elicoidal commented
Runbot and travis are red

2017-04-16 01:04 UTC, elicoidal commented
I am thinking that we should maybe think about migration script but it is complex (cross module).
Nevertheless what I would least do is add a remark in both modules README (Known Issues/Roadmap)  that 
"As of version 8.0.1.0.2, the estimation pricelist has been moved from Project to Partner object. There is no migration script for the change and the data will have to be migrated manually"

2017-04-16 01:08 UTC, elicoidal requested changes

2017-04-16 01:08 UTC, elicoidal commented on business_requirement_deliverable_cost/__openerp__.py
> +    "version": "8.0.1.0.2",
I think we should bump to 8.0.2.0.0 because this modules implies a manual migration of the data

2017-04-18 01:08 UTC, elicoidal commented
> I am thinking that we should maybe think about migration script but it is complex (cross module).
Nevertheless what I would least do is add a remark in both modules README (Known Issues/Roadmap) that
"As of version 8.0.2.0.0, the estimation pricelist has been moved from Project to Partner object. There is no migration script for the change and the data will have to be migrated manually."

@victormartinelicocorp I bumped the version number
Can you update the README and we can merge

2017-04-20 01:35 UTC, elicoidal commented
@victormartinelicocorp can you upload the README so I can fix it?
Please fix travis as well.
then we move forward

2017-04-20 06:26 UTC, victormartinelicocorp commented
@elicoidal done. Please fix Readme and let's see if could merge

2017-04-20 09:24 UTC, elicoidal approved these changes

2017-04-26 03:13 UTC, victormartinelicocorp commented
@elicoidal Could we merge this?

2017-04-26 04:09 UTC, merged