[FIX] business_requirement_deliverable_cost
OCA/business-requirement pull request #134
Opened 2017-05-12 10:59 UTC by victormartinelicocorp

- Fix coversion of UoM
- Fix on_change functions
- Centralize pricelist based product price calculation
- Total revenue from Delirable should be replace by Resources when this module is installed

2017-05-12 11:38 UTC, elicoidal requested changes
some details but overall LGTM
@seb-elico

2017-05-12 11:38 UTC, elicoidal commented on business_requirement_deliverable_cost/models/business.py
> +    def _set_unit_price(self):
_set_cost_price

2017-05-12 11:38 UTC, elicoidal commented on business_requirement_deliverable_cost/models/business.py
> +            br.gross_profit = (
better?
```
br.gross_profit =
                br.total_revenue
                - br.resource_task_total
                - br.resource_procurement_total
```

2017-05-12 11:41 UTC, elicoidal commented on business_requirement_deliverable_cost/models/business.py
> +        for brd in self:
I am not sure this is desired. to be discussed.

2017-05-15 02:20 UTC, seb-elico reviewed
LGTM after Eric's comments are addressed

2017-05-15 02:20 UTC, seb-elico commented on business_requirement_deliverable_cost/models/business.py
> +            br.gross_profit = (
Yes it's easier to read like this IMO (though you still need the parenthesis), unfortunately PEP8 doesn't force this syntax

2017-05-15 03:30 UTC, victormartinelicocorp commented on business_requirement_deliverable_cost/models/business.py
> +            br.gross_profit = (
More human readable IMO. Better to understand

2017-05-15 03:47 UTC, victormartinelicocorp commented
@seb-elico @elicoidal My fuctntional test looks ok and within the other PR #135 

Could you approve these changes?

I'll probable need fix Travis

2017-05-15 04:37 UTC, elicoidal approved these changes

2017-05-15 08:38 UTC, elicoidal commented
OK: Moving forward for the bug fixing

2017-05-15 08:38 UTC, merged