[FIX] business_requirement_deliverable_project_task_categ
OCA/business-requirement pull request #137
Opened 2017-05-15 11:32 UTC by victormartinelicocorp

- Fix View need to be inherited to could see the Category

2017-05-15 11:33 UTC, victormartinelicocorp commented
@elicoidal @seb-elico Please have a look

2017-05-15 13:10 UTC, elicoidal approved these changes

2017-05-15 13:13 UTC, seb-elico requested changes
Almost LGTM

2017-05-15 13:13 UTC, seb-elico commented on business_requirement_deliverable_project_task_categ/views/business_requirement_deliverable.xml
> +                       <field name="categ_id"/>
Could you please fix the indentation of this line?

2017-05-16 04:17 UTC, victormartinelicocorp commented
@seb-elico Please approve if ok

2017-05-16 07:06 UTC, seb-elico approved these changes
@elicoidal @victormartinelicocorp LGTM

2017-05-16 08:31 UTC, dreispt commented on business_requirement_deliverable_project_task_categ/views/business_requirement_deliverable.xml
> +            </field>business_requirement_deliverable_project_task_categ
This line doesn't look right...

2017-05-16 08:31 UTC, dreispt commented on business_requirement_deliverable_project_task_categ/views/business_requirement_deliverable.xml
> +                    <filter string="Category" icon="terp-go-home" context="{'group_by':'categ_id'}"/>
Icons are deprecated, afaict.

2017-05-16 08:31 UTC, dreispt commented on business_requirement_deliverable_project_task_categ/views/business_requirement_deliverable.xml
> +                <xpath expr="//field[@name='resource_ids']/tree[@editable='1']/field[@name='name']"
Is the `[@editable='1']` really needed? Can we get away with a more flexible query, such as `tree[0]`?

2017-05-16 08:59 UTC, elicoidal commented
@victormartinelicocorp please give some love to Travis?

2017-05-16 10:02 UTC, victormartinelicocorp commented
@elicoidal Done.

Also I fixed @dreispt comments.

2017-05-16 10:19 UTC, dreispt approved these changes

2017-05-16 10:20 UTC, merged

2017-05-16 13:56 UTC, elicoidal commented
Tahnks @dreispt !