Readonly always for linked_project
OCA/business-requirement pull request #148
Opened 2017-05-25 08:27 UTC by rubencabrera

As discussed in #146

2017-05-25 08:30 UTC, elicoidal approved these changes

2017-05-26 06:21 UTC, elicoidal commented
@rubencabrera Can you please check travis?

2017-05-26 08:13 UTC, rubencabrera commented
Sure, I'm onto it, seems to be something to do with the product_id onchange, seems related to the recently merged PR, but it was solved there. Let me check.

2017-05-26 08:23 UTC, rubencabrera commented
The test was right, that product_id onchange should still change the description (name field). The mentioned pr was for the deliverable, not the resource.

2017-05-26 13:04 UTC, rubencabrera commented
Ok, the travis fails because a test of business_requirement_deliverable_resource, I was going to change it but I'm not sure which is the expected behaviour.
The test calls product_id_change and asserts that the resource name is equal to the product name, but the function doesn't do that. Should we change it? To do exactly what?

2017-05-27 00:55 UTC, elicoidal commented
Not sure either...
@victormartinelicocorp could you have a quick look?

2017-05-31 07:46 UTC, elicoidal requested changes

2017-05-31 07:46 UTC, elicoidal commented on business_requirement_deliverable/models/business.py
> -        if not self.name:
@rubencabrera 
After reconsidering: why should we have this change in this PR?
I think you need to separate this modification that was done in another PR (may rebase)?
@victormartinelicocorp @darshan-serpent

2017-05-31 09:30 UTC, darshan-serpent commented on business_requirement_deliverable/models/business.py
> -        if not self.name:
@rubencabrera As you know the code for onchange on the resource is already merged in #132 
and the test cases to support it is already added in Open PR #139 check this commit
https://github.com/OCA/business-requirement/pull/139/commits/2a02aedc74743772bff01b9e178b4408f01eae1f

So the travis is already fixed in the above mentioned PR.

So IMO you just need to revert your last commit and that will do all.

cc @elicoidal @victormartinelicocorp

2017-06-01 15:32 UTC, rubencabrera commented on business_requirement_deliverable/models/business.py
> -        if not self.name:
That's what I thought, just wanted to get rid of the annoying travis failing for outside code. I'll revert and commit ASAP. Thanks again to all of you for your input.

2017-06-01 17:02 UTC, darshan-serpent commented
+1

On 01-Jun-2017 21:02, "Rubén" <notifications@github.com> wrote:

> *@rubencabrera* commented on this pull request.
> ------------------------------
>
> In business_requirement_deliverable/models/business.py
> <https://github.com/OCA/business-requirement/pull/148#discussion_r119648567>
> :
>
> > @@ -78,8 +78,6 @@ def product_id_change(self):
>              uom_id = product.uom_id.id
>          if product.description_sale:
>              description += '\n' + product.description_sale
> -        if not self.name:
>
> That's what I thought, just wanted to get rid of the annoying travis
> failing for outside code. I'll revert and commit ASAP. Thanks again to all
> of you for your input.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/business-requirement/pull/148#discussion_r119648567>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATLW4mdsnJkh9anrF0gEi1pwguP-51U5ks5r_tmDgaJpZM4NmGgF>
> .
>

2017-06-03 06:42 UTC, elicoidal commented on business_requirement_deliverable/models/business.py
> -        if not self.name:
@rubencabrera any news?

2017-06-03 11:06 UTC, elicoidal approved these changes

2017-06-03 11:06 UTC, elicoidal commented
Thanks!

2017-06-03 11:06 UTC, merged