[FIX] business_requirement_deliverable_report
OCA/business-requirement pull request #149
Opened 2017-05-25 13:02 UTC by darshan-serpent

## Business Requirement Deliverable Report

Add some of the features of V9 branch within reports

- Added Attachment Feature
- And adjusted Report as per Paperformat

@victormartinelicocorp @elicoidal

2017-05-26 00:51 UTC, elicoidal commented
@darshan-serpent the paper format is way better but you need to take back the PR #139 for all other improvements and fix it with newer fields and structure.

2017-05-26 04:09 UTC, elicoidal requested changes

2017-05-26 04:09 UTC, elicoidal commented on business_requirement_deliverable_report/data/br_report_paperformat.xml
> +        <field name="name">BR Report US Letter</field>
Better by default European A4

2017-05-26 06:21 UTC, elicoidal commented
Can you please check travis?

2017-05-26 10:23 UTC, darshan-serpent commented
@elicoidal Fixed the travis, Please review.

2017-05-26 10:43 UTC, elicoidal commented
@darshan-serpent you are fixing the wrong PR.
We need to get the module fixed in v9 and that @victormartinelicocorp has pushed in #139 
Then we can add your improvements

2017-05-26 10:59 UTC, darshan-serpent commented
@elicoidal Sorry for the trouble. Okay I'll add this changes at the right place.

2017-05-29 05:17 UTC, darshan-serpent commented
Closing the PR as the functionality is already added to #139

2017-05-29 05:17 UTC, closed without merging