[IMP]-Improved Code
OCA/business-requirement pull request #173
Opened 2017-06-08 13:31 UTC by darshan-serpent

#145 This PR resolves the Assignee editable issue.

Changes made : 

- Added a related field to apply the readonly attribute on the fields 
- Removed the bogus/redundant code which was having two views for the BR deliverable and resource

2017-06-08 13:32 UTC, darshan-serpent commented
@elicoidal Could you please review?

2017-06-08 13:34 UTC, dreispt commented on business_requirement_deliverable/views/business_view.xml
> +                        <tree editable="1" >
It's best to leave the Tree view defined it it's own record, rather than defining it inside a field - it makes it easier to extend.

2017-06-09 12:17 UTC, elicoidal commented
@darshan-serpent How to test your modifications?

2017-06-09 12:28 UTC, darshan-serpent commented
Just like the way we were doing before. 

- To create a BR having deliverable and resource lines, which would be editable in 'Draft' and 'Confirm' State
- Then to change the state to 'Stakeholder Approval' which will then only allow to change the `'Assigned To'` field which is on resource lines.

2017-06-19 06:29 UTC, elicoidal approved these changes
Tests LGTM.
Can you attend @dreispt concerns?

2017-06-19 06:55 UTC, darshan-serpent commented on business_requirement_deliverable/views/business_view.xml
> +                        <tree editable="1" >
Yes right, but here we want to display only specific fields having attributes that only remains to this view.

2017-06-19 08:49 UTC, elicoidal commented on business_requirement_deliverable/views/business_view.xml
> +                        <tree editable="1" >
Not sure that I can help here except that I can lose the requirement to make it more flexible later

2017-06-20 05:31 UTC, darshan-serpent commented
@dreispt 
Regarding your comment, I think but here we want to display some specific fields having attributes that only remains to this view so we have added an inner tree view.

What do you suggest? Need your review!!

2017-06-23 01:40 UTC, elicoidal commented
@dreispt @rubencabrera 
Do you have any more feedback? Otherwise I would like to move forward with the PR

2017-06-30 11:28 UTC, darshan-serpent commented
@elicoidal What do you think about this PR?? 

This PR resolves several other issues like https://github.com/OCA/business-requirement/issues/191

2017-06-30 11:41 UTC, elicoidal commented
@victormartinelicocorp @pedrobaeza Could we move forward as @dreispt seems out of office?

2017-06-30 11:44 UTC, pedrobaeza requested changes

2017-06-30 11:44 UTC, pedrobaeza commented on business_requirement_deliverable/models/business.py
> +                             string='State', store=True)
make it readonly=True or you can have problems

2017-06-30 12:09 UTC, darshan-serpent commented on business_requirement_deliverable/models/business.py
> +                             string='State', store=True)
Yes, right!

2017-06-30 13:15 UTC, darshan-serpent commented
@pedrobaeza Your request is attended, could you please review it again?!

2017-06-30 15:34 UTC, pedrobaeza approved these changes

2017-06-30 23:35 UTC, elicoidal commented
@dreispt This points are really blocking for us now so I propose that we move forward.
@darshan-serpent can you add a comment in the code with Daniel's concerns and we merge?

2017-07-01 13:21 UTC, darshan-serpent commented
@elicoidal comment added.

2017-07-02 08:37 UTC, elicoidal commented
Thanks @darshan-serpent

2017-07-03 07:42 UTC, merged