[FIX] [8.0] [i178] Improved reporting BR
OCA/business-requirement pull request #188
Opened 2017-06-28 09:52 UTC by sudhir-serpentcs

@elicoidal  @seb-elico @victormartinelicocorp 
Improved report.

2017-06-28 10:13 UTC, elicoidal commented
#178

2017-06-28 10:15 UTC, elicoidal requested changes
mild details.
I do not see the new menu though nor the modification on the dimension sorting

2017-06-28 10:15 UTC, elicoidal commented on business_requirement_deliverable/report/br_deliverable_sale_report.py
> +        [('draft', 'Draft'), ('confirmed', 'Confirmed'),
better one value per line

2017-07-10 03:38 UTC, elicoidal requested changes
Is sorting of fields in the report view fixed?

2017-07-10 03:38 UTC, elicoidal commented on business_requirement_deliverable_cost/report/br_deliverable_cost_report.py
> +        [('draft', 'Draft'), ('confirmed', 'Confirmed'),
One selection per line to improve readibility

2017-07-10 07:10 UTC, elicoidal commented
@sudhir-serpentcs retested but basically same as before. Besides, it seems that I might have found a calculation bug.
Here is my BR setup in runbot:
![screenshot from 2017-07-10 15-09-35](https://user-images.githubusercontent.com/7600613/28006437-e164f346-6581-11e7-813b-aadc2c385c81.png)

But here is the result in the reports (only one line appears):
![screenshot from 2017-07-10 15-07-33](https://user-images.githubusercontent.com/7600613/28006446-ee4f874c-6581-11e7-9c84-4281f3ca7570.png)
![screenshot from 2017-07-10 15-07-51](https://user-images.githubusercontent.com/7600613/28006447-ee84756a-6581-11e7-9ecb-922c532d717b.png)

2017-07-13 09:01 UTC, elicoidal commented
@sudhir-serpentcs 
New tests failing:
![screenshot from 2017-07-13 17-00-25](https://user-images.githubusercontent.com/7600613/28158616-deeb3f68-67ec-11e7-96a6-90208abe4f98.png)
![screenshot from 2017-07-13 17-00-08](https://user-images.githubusercontent.com/7600613/28158618-df2ca2a0-67ec-11e7-8fd8-c49467e845ca.png)

2017-07-17 07:01 UTC, elicoidal commented
@sudhir-serpentcs Can you recheck everthing because this is still failing basic tests (bases on your data in runbot):

![screenshot from 2017-07-17 14-52-45](https://user-images.githubusercontent.com/7600613/28257796-f5dd05e2-6aff-11e7-8039-f1cb8cc16307.png)
![screenshot from 2017-07-17 14-52-38](https://user-images.githubusercontent.com/7600613/28257797-f5f07e38-6aff-11e7-919b-ee757856dad5.png)
![screenshot from 2017-07-17 14-53-05](https://user-images.githubusercontent.com/7600613/28257798-f6689ad0-6aff-11e7-82f5-ace660c02721.png)

2017-07-19 07:58 UTC, sudhir-serpentcs commented
@elicoidal Could you please review.

2017-07-19 08:57 UTC, elicoidal commented
I retested but it still fails: maybe my requirement is not clear enough.
![screenshot from 2017-07-19 16-56-40](https://user-images.githubusercontent.com/7600613/28358976-5a4710fa-6ca3-11e7-8c22-68eef86982c5.png)
![screenshot from 2017-07-19 16-56-11](https://user-images.githubusercontent.com/7600613/28358977-5a60fb00-6ca3-11e7-8bda-5c1a9bf5893c.png)
![screenshot from 2017-07-19 16-56-04](https://user-images.githubusercontent.com/7600613/28358979-5b4a4026-6ca3-11e7-85b0-7eeaa5e02384.png)

Let me know if you need a call

2017-07-19 11:27 UTC, sudhir-serpentcs commented
@elicoidal I think we need to discuss on call.

2017-07-20 11:41 UTC, sudhir-serpentcs commented
@elicoidal Please test the report and review.

As per our discussion on call, you gave following calculation:

**Total Revenue = DL Sales Price * DL Qty
Sales Price = Total Revenue / DL Qty**
Here sales price and total revenue will be same.

---
Same goes for Avg Price and Total Cost:
**Total Cost = RL Price * RL Qty
Avg Price = Total Cost / RL Qty**
Here as well total cost and avg price will be same.

Let me know if you want me to change the calculation or let it be as per our discussion
![dl_cost_analysis](https://user-images.githubusercontent.com/13166978/28415694-6fef811e-6d6e-11e7-9955-4f69ef4fc88f.png)

2017-07-21 01:11 UTC, elicoidal commented
@sudhir-serpentcs I have had a lot of reflexion about the reporting topic and I will close this PR for the following reasons:
* We still cannot stabilize it
* But most important, this is somehow duplicated with the pivot view in BRDL and BRRL

I prefer to improve the other 2 views accordingly forget about this one.

2017-07-21 01:11 UTC, closed without merging