[IMP][8.0][22070][ISSUE#115]-Improved code as per changes
OCA/business-requirement pull request #192
Opened 2017-06-29 12:10 UTC by darshan-serpent

Issue #115

- Added Smart button Linked Project.

- Added two fields business_requirement_id and business_requirement_deliverable_id in project.project.

- Make invisible linked_project field form BR.

-  Made read-only field for_br while generated projects wizard is open.

@seb-elico @elicoidal @victormartinelicocorp

2017-06-30 01:50 UTC, elicoidal commented
@darshan-serpent thanks for the contribution.
I made a test with one BR, 2 deliverables and created the projects from both BR + deliverables:
- [ ] In created project: cannot use the BR smart button to display the linked BR (nothing listed)
- [ ] in original BR, Linked Project smart button only shows the project directly linked to the BR, not the ones linked to deliverables (expected shows all projects linked to the BR and its deliverable)

Rest looks good but I still need a test on BR with sub-BR
cc @seb-elico @victormartinelicocorp

2017-06-30 02:42 UTC, elicoidal commented
Test with Children project are similar to the one with Deliverables

Problem while copying:
- [ ] when copying a BR, the copied BR is still linked to the project of the initial BR (??)

2017-06-30 07:37 UTC, darshan-serpent commented
@elicoidal Regarding creating projects from Deliverables.

I am not really sure how to create a project from deliverables, can you please describe it in brief?!

2017-07-07 01:11 UTC, elicoidal commented
@darshan-serpent What is the situation on this BR?

2017-07-10 03:28 UTC, elicoidal commented
@darshan-serpent @sudhir-serpentcs What is the situation here?

2017-07-10 03:45 UTC, darshan-serpent commented
@elicoidal There's still some confusion here, I'll let you know the details soon of current situation.

2017-07-10 12:29 UTC, YogeshMahera-SerpentCS commented
@elicoidal 
Could you please review it.

2017-07-11 10:03 UTC, elicoidal commented
Small details:

- [ ] in smart button BR in project: the number of BR should not be displayed (a project can only be linked to one BR at a time)
- [ ] in BR "Linked Project" should display the number of linked project.

Rest looks OK!

2017-07-11 10:03 UTC, elicoidal commented
@victormartinelicocorp

2017-07-11 10:53 UTC, martintorresvm requested changes
Others LGTM

2017-07-11 10:53 UTC, victormartinelicocorp commented on business_requirement_deliverable_project/models/business.py
> +    def open_linked_projects(self):
@darshan-serpent This returns type action so the name need to be according:
s/open_linked_projects
r/action_open_linked_projects

2017-07-11 10:53 UTC, victormartinelicocorp commented on business_requirement_deliverable_project/models/project.py
> +    def open_linked_br_dl(self):
@darshan-serpent This returns type action so the name need to be according:
s/open_linked_br_dl
r/action_open_linked_br_dl

2017-07-12 04:47 UTC, YogeshMahera-SerpentCS commented
@victormartinelicocorp could please review.

2017-07-13 07:55 UTC, elicoidal commented
@YogeshMahera-SerpentCS Can you recheck Travis?

2017-07-17 05:46 UTC, YogeshMahera-SerpentCS commented
@elicoidal Travis Green

2017-07-17 06:37 UTC, elicoidal commented
@darshan-serpent I still see many issues with smart buttons in Project and the more I think about the more I think this is anyway a mistake create a smart button for this kind of field: it should be a simple m2o field right (for one given project, there could only be one BR, right?) ? If so I would put it below customer in the project form
cc @victormartinelicocorp @sudhir-serpentcs

2017-07-19 01:46 UTC, elicoidal commented
@sudhir-serpentcs any feedback on this?

2017-07-21 08:31 UTC, YogeshMahera-SerpentCS commented
@elicoidal Could you please review

2017-07-21 09:06 UTC, elicoidal approved these changes
@YogeshMahera-SerpentCS LGTM!

2017-07-21 09:07 UTC, elicoidal commented
@victormartinelicocorp @dreispt @pedrobaeza Thanks for your review

2017-07-21 09:55 UTC, victormartinelicocorp commented on business_requirement_deliverable_project/models/business.py
> +            domain = ['|',
@darshan-serpent @YogeshMahera-SerpentCS Need to understand the exactly purpose of this domain?
This two fields:
`business_requirement_id`
`business_requirement_deliverable_id`

As parameters domains means should be fields on the `business.requirement` model, right?

2017-07-21 10:13 UTC, martintorresvm approved these changes
thanks @darshan-serpent @sudhir-serpentcs

2017-07-24 10:23 UTC, merged

2017-08-23 06:52 UTC, victormartinelicocorp commented
@elicoidal @seb-elico As you know we could see just the code that changes when it's created a PR. 

@YogeshMahera-SerpentCS Please it's very important to be sure and understand the scope. So if the topic is `Modify projects and BR id relationship` how comes that still exists `linked_project` fields on BR and BRD?

Furthermore on wizard for generate projects still exist check and assignations that depends on `linked_project`. 

Others smalls details, that could be quick correct.

Now we have and issue #241 and now I have to review the whole code and check whether is new or old modification.