[IMP]  [8.0-i193-BR001028-T22320] Added code to search BR based on Name or Description in m2o fields
OCA/business-requirement pull request #203
Opened 2017-06-30 11:30 UTC by sudhir-serpentcs

This PR refers to Issue #195 
@elicoidal @seb-elico @victormartinelicocorp Please review.

2017-06-30 11:43 UTC, elicoidal approved these changes

2017-07-10 03:30 UTC, elicoidal commented
@victormartinelicocorp

2017-07-13 08:22 UTC, martintorresvm requested changes

2017-07-13 08:22 UTC, victormartinelicocorp commented on business_requirement/models/business.py
> +        names1 = super(BusinessRequirement, self).name_search(
@sudhir-serpentcs Since a while I haven't see a variable with numbers.

think this could named `names`
second one `descriptions`

@elicoidal ?

2017-07-13 09:15 UTC, sudhir-serpentcs commented on business_requirement/models/business.py
> +        names1 = super(BusinessRequirement, self).name_search(
@victormartinelicocorp Done. Changed the variable names.

2017-07-13 09:43 UTC, martintorresvm approved these changes

2017-07-17 06:41 UTC, merged