[8.0]-[BR1030]-[ADD/IMP][Reference field improvements]
OCA/business-requirement pull request #208
Opened 2017-07-03 09:51 UTC by darshan-serpent

Issue:- #184 

- Improved string reference to "WBS"

- Improved name_get method

- Added origin field with text type

@elicoidal @victormartinelicocorp

2017-07-03 10:09 UTC, elicoidal approved these changes
LGTM 
@victormartinelicocorp @seb-elico

2017-07-03 10:09 UTC, elicoidal commented on business_requirement/models/business.py
>          readonly=True,
Any reason why r/o?

2017-07-03 10:13 UTC, martintorresvm requested changes

2017-07-03 10:13 UTC, victormartinelicocorp commented on business_requirement/models/business.py
> +                formatted_name = u'[{}][{}] {}'.format(br.ref, br.name,
@darshan-serpent What is the point of have twice the br.name? Perhaps you forgot add other field?

2017-07-03 10:15 UTC, darshan-serpent commented on business_requirement/models/business.py
>          readonly=True,
Hmm.. I haven't changed it was already there.

But yes, I think read-only should not be there, should I remove?

2017-07-03 10:22 UTC, darshan-serpent commented on business_requirement/models/business.py
> +                formatted_name = u'[{}][{}] {}'.format(br.ref, br.name,
Yes you are right. I think It should be like, right? 

`formatted_name = u'[{}] {}'.format(br.ref, br.name, br.description)`

Will do the needful, thanks!

2017-07-03 10:34 UTC, elicoidal commented on business_requirement/models/business.py
>          readonly=True,
I am not sure as there are some ACL based on status. I dont know if it has an impact so dont modify it here.

2017-07-03 10:37 UTC, elicoidal commented on business_requirement/models/business.py
> +                formatted_name = u'[{}][{}] {}'.format(br.ref, br.name,
not sure here but if the requirement is fulfilled, this is fine by me.

I want: [WBS][name] Description or [name] Description (if WBS empty)

2017-07-03 10:39 UTC, victormartinelicocorp commented on business_requirement/models/business.py
> +                formatted_name = u'[{}][{}] {}'.format(br.ref, br.name,
:+1:

2017-07-03 11:27 UTC, darshan-serpent commented
@elicoidal @victormartinelicocorp Tested on runbot, works as expected.

The test is made with 2 BRs, one with WBS and other without it.

![without_wbs](https://user-images.githubusercontent.com/20109026/27790896-2cd050a4-6010-11e7-9606-a61032588b4b.png)
![with_wbs](https://user-images.githubusercontent.com/20109026/27790897-2cd8eb10-6010-11e7-985b-ba3b1756bb88.png)

2017-07-03 12:06 UTC, elicoidal approved these changes
Perfect!

2017-07-03 12:06 UTC, elicoidal commented
@victormartinelicocorp please review again

2017-07-04 03:27 UTC, martintorresvm approved these changes

2017-07-10 03:31 UTC, merged