[WIP][8.0][BR001024] - Added demo data for BR modules
OCA/business-requirement pull request #212
Opened 2017-07-05 06:36 UTC by darshan-serpent

[WIP]

- Added demo data for BR modules

2017-07-06 14:04 UTC, darshan-serpent commented
Please review it
@elicoidal @victormartinelicocorp 
cc
@sudhir-serpentcs

2017-07-07 01:12 UTC, elicoidal commented
Tests: 
- [ ] Products in deliverables and resources lines seems all wrong (Probably linked to commented code)
- [ ] In BR Business Analysis deliverables, please change 800 => 50 and 2000 by 45
- [ ] In BR Gap analysis deliverables, please change 800 => 50 and 0 => 35
- [ ] Category for all products should be "All / Saleable / Services"
- [ ] I dont know why but I have 2 tabs "Default Resource lines" in Product form
- [ ] WEB02 is missing some resources lines
- [ ] For BR and Project category, please change from "CAPS" to "Normal" (SYSTEM => System)

To be tested after #192 is merged as there might be some light changes in the structure.

2017-07-10 03:36 UTC, elicoidal requested changes

2017-07-10 03:36 UTC, elicoidal commented on business_requirement/__openerp__.py
> +        'portal'
I dont want to add one extra dependency only for demo data.
Please change the Demo Portal user to Admin User

2017-07-10 03:36 UTC, elicoidal commented on business_requirement_deliverable_resource_template/data/business_requirement_deliverable_resource_template.xml
> +<?xml version="1.0" encoding="utf-8"?>
File name

2017-07-10 03:36 UTC, elicoidal commented on business_requirement_deliverable_resource_template/data/business_requirement_deliverable_resource_template.xml
> +<!--             <field name="product_id" ref="product_1"/> -->
remove dead code

2017-07-11 07:49 UTC, YogeshMahera-SerpentCS commented
@elicoidal could you please review.please correct me if I am wrong

> Products in deliverables and resources lines seems all wrong (Probably linked to commented code)
- Probably code has improved but needs review

> In BR Business Analysis deliverables, please change 800 => 50 and 2000 by 45
- Changed Values 

> In BR Gap analysis deliverables, please change 800 => 50 and 0 => 35
- Changed Values 

> Category for all products should be "All / Saleable / Services"
- product.product default product category  is `All` so no need to change

>  I dont know why but I have 2 tabs "Default Resource lines" in Product form

- I have seen there is  same name `resource_lines` used but different models 

- one resource_lines for `business.requirement.resource` object and

- second one resource_lines for `business.requirement.resource.template` with the same name

- so i have improved second number one2many  from `resource_lines`  to  `resource_template_lines`

> WEB02 is missing some resources lines

- Improved code
> For BR and Project category, please change from "CAPS" to "Normal" (SYSTEM => System)

- Improved code in `business.requirement.category` and  `project.category.main` for demo data

2017-07-11 10:16 UTC, elicoidal commented
@darshan-serpent @YogeshMahera-SerpentCS 
Still some glitches:
- [ ] First 2 deliverables are not linked to products ([BR000001] Corporate Website and [BR000003] ERP Setup)
- [ ] in product there should be only one tab "Resource template lines" (I dont know what is the second one)
- [ ] change "Website product" name to "Website Template"
- [ ] in task category change Pm to PM
- [ ] I cannot see any RL template in the products
- [ ] Change the product category as suggested
- [ ] (not sure this is for this PR): The cost control tab is wrong (no total for tasks)

2017-07-11 12:34 UTC, YogeshMahera-SerpentCS commented
>First 2 deliverables are not linked to products ([BR000001] Corporate Website and [BR000003] ERP Setup)
@elicoidal which product should be linked ?

- Developer
- Designer
- Consultant
- Website Template 
- Website Design
- Odoo Quick Start Package

2017-07-12 00:42 UTC, elicoidal commented
@YogeshMahera-SerpentCS please refer to the original documentation (mail):
A.
Description= Corporate Website
Responsible = Admin
Priority =2
Category=WEBSITE, DESIGN
Reviewer=Demo
To be Reviewed= True
Stage=Confirmed
Customer= Agrolait
Deliverable: use Website Design product (Quantity = 1, Sales Price=5200)
Product=[E-COM09] iMac, quantity = 1 unit, type = Procurement, name=Server
Product=[WEB01] Website Template, Quantiy=1 unit, type=Procurement, name=Beautiful template
product=Designer (Name = Customer design assistance, 3 days, Task, assigned to Demo Portal, Task category= DESIGN, cost=35, unit sales price=60)
Product=Developer (Name = Interface Development, 7 days, Task, assigned to Demo, Task category= DEVELOPMENT, cost=25, unit sales price=35)

C.
Description= Server Set up
Responsible = Demo
Priority =2
Category=ERP, INFRA
Reviewer=Demo Portal
To be Reviewed= False
Parent BR = ERP Implementation
Stage=Stakeholder
Customer= Yourcompany
Deliverable: Product= Developer, Name=Server Setup, 8h
Product=Developer (Name= Server Setup, 8h, Task, assigned to Demo, Task category= DEVELOPMENT, cost=25, unit sales price=35)

2017-07-12 09:48 UTC, YogeshMahera-SerpentCS commented
>  I cannot see any RL template in the products

@elicoidal 
I don't get this point.

2017-07-12 12:20 UTC, elicoidal commented
@YogeshMahera-SerpentCS no. Template lines should contain the default value I have provided you.
This template lines are added to the BR resources when the deliverable is selected.
cc @sudhir-serpentcs 

for example:
 E.
Name= Website Design
Internal Ref=WEB02
Unit=unit
Type=service
Cost =3500
Sales price = 5200
Contains following template Resource lines
Product=[E-COM09] iMac, quantity = 1 unit, type = Procurement, name=Server
Product=[WEB01] Website Template, Quantiy=1 unit, type=Procurement, name=Beautiful template
product=Designer (Name = Customer design assistance, 3 days, Task, assigned to Demo Portal, Task category= DESIGN, cost=35, unit sales price=60)
Product=Developer (Name = Interface Development, 7 days, Task, assigned to Demo, Task category= DEVELOPMENT, cost=25, unit sales price=35)

F.
Name=Odoo Quick Start Package
Internal Ref=OD01
Sales Price = 4000
Cost Price = 1500
Contains following template Resource lines
Product=consultant (Name= Functional Analysis, 24h, Task, assigned to Admin, Task category= ANALYSIS, cost=30, unit sales price=50)
Product=developer (Name=Technical Support, 32h, Task, assigned to Demo, Task category= DEVELOPMENT, cost=25, unit sales price=35)

2017-07-17 05:47 UTC, YogeshMahera-SerpentCS commented
@elicoidal Could please review.

2017-07-17 07:01 UTC, elicoidal commented
@YogeshMahera-SerpentCS still many problems:

- [ ] Tasks Category are missing
![screenshot from 2017-07-17 14-54-48](https://user-images.githubusercontent.com/7600613/28257790-f01d229a-6aff-11e7-9505-d957a8f259c8.png)

- [ ] Website Design and Odoo Quick Start Package product are duplicated
- [ ] Deliverable Server Setup price should be 35
- [ ] Many resources lines are missing in BR (eg: Business Analysis)
etc.

2017-07-19 01:47 UTC, elicoidal commented
@YogeshMahera-SerpentCS is it testable?

2017-07-19 04:17 UTC, YogeshMahera-SerpentCS commented
@elicoidal Still **WIP**
Once will update you.

2017-07-19 13:32 UTC, YogeshMahera-SerpentCS commented
@elicoidal Could please test it again

2017-07-21 06:42 UTC, elicoidal commented
@YogeshMahera-SerpentCS Almost there!
- [ ] on BR0001:
* A1090: in RL sale price should be 1799, cost 1299
 *Web01: Sales price: 150/Cost: 100
* SER01: Sales price: 280/200
* SER02: Sales Price:480/280
- [ ] in BR003 / Deliverable, Cost control information is wrong (not sure this is a demo data issue though)
![screenshot from 2017-07-21 14-29-24](https://user-images.githubusercontent.com/7600613/28451664-2132a1b0-6e21-11e7-8e04-a2884f5f51f2.png)

- [ ] SO0008 Unit price should be 50 and 45 (instead of 800 and 2000)

@sudhir-serpentcs @darshan-serpent I think we might need to wait for #192 to be merge, then rebase and probably fix the project link to the BR
cc @victormartinelicocorp can you review?

2017-07-21 07:00 UTC, elicoidal commented
Another small additional topic. Can you add the following text when the screen of BR is empty (Please format it as a list for the second part of the message):
![screenshot from 2017-07-21 14-56-45](https://user-images.githubusercontent.com/7600613/28452340-daa72046-6e24-11e7-94ad-67862820c4ce.png)

         <p class="oe_view_nocontent_create">
            Click to start a new purchase request process. 
          </p><p>
A Business requirement (BR) is the expression of a business need by a customer or internal project user.
A BR contains multiple different parts to explain the stakeholder need and how to meet his/her requirements:

    Customer Story: this is the requirement as expressed by the customer
    Scenario: How/where the current solution can provide a suitable scenario to answer the customer story
    Gap: For the uncovered part of the scenario, elaborate the gap/need for specific developments/setup
    Test case: A set of conditions under which a tester will determine whether the application, software system or one of its features is working as it was originally established for it to do.
    Deliverables to be provided to the customer/user
    Resources necessary to achieve the deliverables
    Additional information (approval, cost control etc.)

          </p>

2017-07-21 09:56 UTC, YogeshMahera-SerpentCS commented
>  in BR003 / Deliverable, Cost control information is wrong (not sure this is a demo data issue though)

I can not find any wrong data same

Description= ERP Setup
Responsible = Demo
Priority =1
Category=ERP
Reviewer=Demo Portal
To be Reviewed= False
Parent BR = ERP Implementation
Stage=Approved
Customer= Yourcompany
Deliverable: use Odoo Quick Start (Qty=1, Sales Price=4000)
Add all resources:
Product=consultant (Name= Functional Analysis, 24h, Task, assigned to Admin, Task category= ANALYSIS, cost=30, unit sales price=50)
Product=developer (Name=Technical Support, 32h, Task, assigned to Demo, Task category= DEVELOPMENT, cost=25, unit sales price=35)

![dl](https://user-images.githubusercontent.com/24264979/28458866-dcc7b3be-6e28-11e7-8000-d0a5f584142d.png)
@elicoidal

2017-07-21 10:23 UTC, elicoidal commented
@YogeshMahera-SerpentCS 
in above example you provided, in the deliverable header, Total tasks should be 1520, Gross Profit should be 4000-1520 = 3480
![screenshot from 2017-07-21 18-23-06](https://user-images.githubusercontent.com/7600613/28459832-b9569918-6e41-11e7-8dc1-18b7b96d2005.png)
Let me know if unclear

2017-07-21 10:42 UTC, YogeshMahera-SerpentCS commented
Total tasks is 1520,
Gross Profit is 4000-1520 = 2480

![test1](https://user-images.githubusercontent.com/24264979/28460365-57d8eeaa-6e2f-11e7-999c-82acc0ba1f9d.png)

2017-07-21 10:46 UTC, elicoidal commented
Did you fix SO008 too?

2017-07-21 11:08 UTC, YogeshMahera-SerpentCS commented
yes fixed SO008

2017-07-21 11:32 UTC, elicoidal commented
SO008 is OK but not the Cost control.
By the way, SO008 is validated: it should be in draft state
@YogeshMahera-SerpentCS

2017-07-21 12:18 UTC, YogeshMahera-SerpentCS commented
SO008 is on draft stage

2017-07-24 05:06 UTC, YogeshMahera-SerpentCS commented
@elicoidal Could you please review again

2017-07-24 10:21 UTC, elicoidal commented
@YogeshMahera-SerpentCS The cost control tab is still wrong.
SO0008 status is OK
in the following screenshot, expected task total = 480 (same would be true for procurement if any in the resources lines)
![screenshot from 2017-07-24 18-20-31](https://user-images.githubusercontent.com/7600613/28519093-ddb39e70-709c-11e7-99cd-96b18a302651.png)

cc: @sudhir-serpentcs

2017-07-24 12:22 UTC, YogeshMahera-SerpentCS commented
@elicoidal 
Yes, just checked and I already made changes in py files.

![test3](https://user-images.githubusercontent.com/24264979/28523188-d80a7e02-7098-11e7-9196-44026492848a.png)

2017-07-25 00:40 UTC, elicoidal approved these changes
LGTM!
@victormartinelicocorp @seb-elico Please review

2017-07-25 00:41 UTC, elicoidal commented on business_requirement_deliverable_resource_template/__openerp__.py
> +        'data/business_requirement_deliverable_resource_template_data.xml'
should be _demo

2017-07-25 00:42 UTC, elicoidal commented on business_requirement_deliverable_resource_template_categ/__openerp__.py
> +        "business_requirement_deliverable_resource_template_categ_data.xml",
should be _demo

2017-07-25 03:06 UTC, victormartinelicocorp commented on business_requirement_deliverable_cost/models/business.py
> +    @api.depends('resource_ids', 'resource_ids.price_total')
@darshan-serpent This should be part of another PR.

Seems not too big changes and makes sense so at least I would like know if it's documented this Issue or what is about. Could you add some reference?

2017-07-25 04:14 UTC, elicoidal commented on business_requirement_deliverable_cost/models/business.py
> +    @api.depends('resource_ids', 'resource_ids.price_total')
@victormartinelicocorp This is documented in the conversation but not in a formal issue.
I would keep it here for the sake of simplicity

2017-07-25 05:26 UTC, victormartinelicocorp commented on business_requirement_deliverable_cost/models/business.py
> +    @api.depends('resource_ids', 'resource_ids.price_total')
@elicoidal Was just a nice to have, the others LGTM

2017-07-25 05:28 UTC, martintorresvm approved these changes

2017-07-26 10:20 UTC, seb-elico requested changes

2017-07-26 10:20 UTC, seb-elico commented on business_requirement_deliverable_resource_template_categ/data/business_requirement_deliverable_resource_template_categ_demo.xml
> +                <field name="categ_id"
Could you please fix the indentation of this line? `field` is child of `record` (same for all the document)

2017-07-26 10:21 UTC, seb-elico commented
@darshan-serpent @victormartinelicocorp any reason why the coverage has decreased?

2017-07-26 10:27 UTC, victormartinelicocorp commented
> @darshan-serpent @victormartinelicocorp any reason why the coverage has decreased?

@seb-elico Modify functions not covered:
https://github.com/OCA/business-requirement/pull/212/files#diff-63f164bb06a74e20b85ab6efc5bb42ffR125

Coverage still quite good but sure @darshan-serpent could fix it.

2017-07-26 13:15 UTC, YogeshMahera-SerpentCS commented
@victormartinelicocorp @seb-elico

2017-07-27 11:00 UTC, seb-elico approved these changes
LGTM

2017-07-27 11:36 UTC, merged