[I-199][BR1028][IMP]Improved Project Creation Process
OCA/business-requirement pull request #216
Opened 2017-07-12 12:34 UTC by YogeshMahera-SerpentCS

Issue #199 

- Project Created BR with RL,without DL

2017-07-13 00:29 UTC, elicoidal commented
@YogeshMahera-SerpentCS functional tests failed:
I created one BR with 1 DL (containing 2 RL) and 1 extra RL.
Created the project: 2 tasks are created
Expected: 3 tasks are created

2017-07-13 08:59 UTC, YogeshMahera-SerpentCS commented
Yes, the Improved code, could you please review.
@elicoidal

2017-07-13 09:05 UTC, elicoidal approved these changes
@YogeshMahera-SerpentCS Tests LGTM
@victormartinelicocorp

2017-07-17 06:48 UTC, elicoidal commented
@dreispt @pedrobaeza Can you help?

2017-07-17 09:27 UTC, pedrobaeza requested changes

2017-07-17 09:27 UTC, pedrobaeza commented on business_requirement_deliverable_project/models/project.py
> +                lines.append(resource_line.id)
Use a recordset instead:
```
lines = env['...']
...
lines |= resource_line
```

2017-07-17 09:27 UTC, pedrobaeza commented on business_requirement_deliverable_project/wizard/generate_projects.py
> +            lines = [br.resource_lines]
Why encapsulating this in another list?

2017-07-17 09:27 UTC, pedrobaeza commented on business_requirement_deliverable_project/models/project.py
> +            for resource_line in br.resource_lines:
```
for resource_line in br.resource_lines.filtered(
    lamba x: x.resource_type == 'task'
):
```

2017-07-19 01:59 UTC, elicoidal commented
@YogeshMahera-SerpentCS @victormartinelicocorp

2017-07-19 05:53 UTC, victormartinelicocorp commented
@YogeshMahera-SerpentCS Any problem to fix the code with @pedrobaeza review?

2017-07-21 03:46 UTC, victormartinelicocorp commented
@YogeshMahera-SerpentCS Please increase coveralls

2017-07-21 06:45 UTC, elicoidal commented
@pedrobaeza can we move forward?

2017-07-21 06:45 UTC, elicoidal commented
@victormartinelicocorp I think coverall is decent enough

2017-07-21 07:13 UTC, pedrobaeza approved these changes

2017-07-21 07:13 UTC, merged

2017-07-21 07:21 UTC, elicoidal commented
Thanks @pedrobaeza !