[8.0]-IMP-Stages as clickable
OCA/business-requirement pull request #227
Opened 2017-07-31 09:43 UTC by YogeshMahera-SerpentCS

- Stages as clickable in BR main module
- Removed code unnecessary code.

2017-07-31 10:08 UTC, elicoidal commented
Please check travis

2017-07-31 11:59 UTC, YogeshMahera-SerpentCS commented
@elicoidal Can you please review.

2017-08-01 01:20 UTC, elicoidal approved these changes
Functional tests OK

2017-08-01 01:21 UTC, elicoidal commented
@victormartinelicocorp @seb-elico

2017-08-04 03:27 UTC, martintorresvm requested changes

2017-08-04 03:27 UTC, victormartinelicocorp commented on business_requirement/models/business.py
> +    def read_group(self, domain, fields, groupby, offset=0,
@YogeshMahera-SerpentCS Add docstring:

- [ ] Short functionality description
- [ ] Input
- [ ] Ouput

2017-08-04 06:26 UTC, seb-elico approved these changes
LGTM after adding docstring

2017-08-04 08:52 UTC, YogeshMahera-SerpentCS commented
@victormartinelicocorp 
Added docstring

        """ Read group customization in order to display all the stages in the
            kanban view. if the stages values are there it will group by state.
        """

2017-08-04 09:01 UTC, martintorresvm approved these changes

2017-08-04 09:14 UTC, merged