[IMP]-Improved code
OCA/business-requirement pull request #230
Opened 2017-08-01 12:54 UTC by YogeshMahera-SerpentCS

-Improvements of Linked Project Smart Buttons from BR form view.

2017-08-02 00:34 UTC, elicoidal approved these changes
LGTM Functional tests
@seb-elico @victormartinelicocorp

2017-08-04 03:34 UTC, martintorresvm approved these changes

2017-08-04 06:27 UTC, seb-elico requested changes

2017-08-04 06:27 UTC, seb-elico commented on business_requirement_deliverable_project/models/business.py
> +    def _compute_linked_project_count(self):
Add docstring

2017-08-04 09:45 UTC, merged