[10.0]-[MIG]-Migrated module from v8 to v10 Business_requirement_deliverable_project_task_categ
OCA/business-requirement pull request #233
Opened 2017-08-02 13:12 UTC by YogeshMahera-SerpentCS

**WIP**
#48 
- Business_requirement_deliverable_project_task_categ

2017-08-03 10:19 UTC, YogeshMahera-SerpentCS commented
Notes:- 
effective_hours
In v8 that field is available in project module but later on v9 it's moved on `project_timesheet`,
now in v10, it's again moved to hr_timesheet.

So added hr_timesheet dependency in `business_requirement_deliverable_project` project.

2017-09-18 06:41 UTC, elicoidal commented
@YogeshMahera-SerpentCS I tested it but could not find the categories anywhere in the Resources lines. Did I miss something?

2017-09-20 01:44 UTC, elicoidal commented
@YogeshMahera-SerpentCS

2017-09-20 06:49 UTC, YogeshMahera-SerpentCS commented
@elicoidal 
I think this PR depends on #231(BR Project module)
So We have to wait for merge.

2017-09-20 07:12 UTC, elicoidal commented
OK: let's try to fix all other PR first :smile:

2017-10-04 07:04 UTC, elicoidal commented
I think you can rebase this one as the data model in #231 should be stable now

2017-10-04 12:12 UTC, YogeshMahera-SerpentCS commented
rebased

2017-10-05 04:58 UTC, elicoidal commented
Can you check travis?

2017-10-25 06:16 UTC, elicoidal commented
@YogeshMahera-SerpentCS can you rebase as #231 is merged so that we can finish this one?

2017-10-25 13:28 UTC, YogeshMahera-SerpentCS commented
@elicoidal rebased

2017-10-26 01:25 UTC, elicoidal commented
Thanks @YogeshMahera-SerpentCS
Seems travis and runbot are both failing: can you have a look?

2017-10-26 02:30 UTC, victormartinelicocorp commented
@YogeshMahera-SerpentCS 

ParseError: "categ_id" while parsing /home/travis/build/OCA/business-requirement/business_requirement_deliverable_project_task_categ/data/business_requirement_deliverable_project_task_categ_demo.xml:20, near

2017-10-26 05:36 UTC, YogeshMahera-SerpentCS commented
Yes I already checked this one in  my local it's seems everything OK. but I am going to check deep.

2017-10-26 10:03 UTC, YogeshMahera-SerpentCS commented
@elicoidal @victormartinelicocorp Could you please review it

2017-10-26 10:29 UTC, martintorresvm requested changes

2017-10-26 10:29 UTC, victormartinelicocorp commented on business_requirement_deliverable_project_task_categ/models/business_requirement_resource.py
> +        'project.tags',
@YogeshMahera-SerpentCS Please use this reference and update related:

https://github.com/OCA/project/blob/10.0/project_task_category/models/project_task.py#L14

2017-10-26 10:41 UTC, elicoidal reviewed
Are they tests?

2017-10-26 11:21 UTC, YogeshMahera-SerpentCS commented
@victormartinelicocorp Could you please check it

2017-10-27 00:35 UTC, elicoidal approved these changes
Functional tests OK

2017-10-27 00:35 UTC, elicoidal commented
@victormartinelicocorp

2017-10-27 07:10 UTC, martintorresvm approved these changes
LGTM

2017-10-27 10:30 UTC, merged