[10.0][IMP]-Migrated Business requirement etherpad module from v8 to v10.
OCA/business-requirement pull request #235
Opened 2017-08-03 11:55 UTC by YogeshMahera-SerpentCS

#48 

- Migrated Business requirement etherpad module from v8 to v10.

2017-08-04 00:43 UTC, elicoidal approved these changes
LGTM
@seb-elico @victormartinelicocorp

2017-08-04 03:46 UTC, victormartinelicocorp commented
@elicoidal I could review it but think would be better as soon #223 is merged so Travis, Coveralls, Runbot are operative.

2017-08-04 06:35 UTC, seb-elico requested changes

2017-08-04 06:35 UTC, seb-elico commented on business_requirement_etherpad/views/business_view.xml
> +                <xpath expr='//page[1]' position='after'>
- [ ] use `"` as attribute separator
- [ ] why using absolute index instead of the tab name?

2017-08-09 10:07 UTC, seb-elico requested changes

2017-08-09 10:07 UTC, seb-elico commented on business_requirement_etherpad/views/business_view.xml
> +                <xpath expr='//page[@name="logs"]' position='before'>
Use `"` to encapsulate tag parameters

2017-08-09 10:29 UTC, martintorresvm approved these changes
After @seb-elico comments fixed. LGTM

2017-08-14 06:29 UTC, seb-elico approved these changes
LGTM

2017-08-14 10:34 UTC, merged