9.0 16334 migrate business requirement
OCA/business-requirement pull request #25
Opened 2016-09-23 11:06 UTC by sudhir-serpentcs

Migrated business_requirement module from v8 to v9.

2016-09-23 11:54 UTC, elicoidal commented on business_requirement/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/222/8.0
9.0

2016-09-23 11:55 UTC, elicoidal commented on business_requirement/README.rst
> +   .. figure::business_requirement/static/img/bus_req_tags2.png
For all pictures, keep only one remove business_requirement/

2016-09-23 11:56 UTC, elicoidal commented on business_requirement/models/business.py
> +        if not company_id:
I think this should never happen as company is mandatory.

2016-09-23 11:58 UTC, elicoidal requested changes
some details in README . :+1:

2016-09-24 01:26 UTC, elicoidal commented
tested in runbot: :+1:

2016-09-24 02:21 UTC, moylop260 commented on business_requirement/models/business.py
> +        default=_get_default_company,
What about use the following way https://github.com/odoo/odoo/blob/b2804b1d2ae5fd7ec5c0eca79a8db77476badc84/addons/account/models/account.py#L192?

`company_id = fields.Many2one('res.company', string='Company', required=True, index=True, default=lambda self: self.env.user.company_id,
        help="Company related to this journal")`

2016-09-26 07:17 UTC, sudhir-serpentcs commented on business_requirement/models/business.py
> +        if not company_id:
Yes, I do agree with you.
I will remove it.

2016-09-26 07:32 UTC, sudhir-serpentcs commented
Removed duplicate images from README and added anonymous function to get default company.

2016-09-26 07:33 UTC, sudhir-serpentcs commented
Next: Replace old screenshots in README by new ones for v9.

2016-09-26 10:27 UTC, elicoidal commented
True and add some simple demo data as well ( @sudhir-serpentcs )

2016-09-29 07:18 UTC, elicoidal commented
@sudhir-serpentcs demo data can be done in second stage. Can you resubmit with newer screenshot so that we have it reviewed and merged?

2016-09-29 14:47 UTC, moylop260 requested changes

2016-09-29 14:47 UTC, moylop260 commented on business_requirement/models/business.py
> +        if self.project_id and self.project_id.partner_id:
What about use:

``` diff
- if self.project_id and self.project_id.partner_id:
-      self.partner_id = self.project_id.partner_id.id
+ self.partner_id = self.project_id.partner_id.id
```

Now the new api support `BrowseNull.BrowseNull` and IMHO this onchange should change in order to avoid use a old value of other onchange.

2016-09-29 14:47 UTC, moylop260 commented on business_requirement/models/business.py
> +    name = fields.Char(string='Name', required=True)
FYI https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#field
`If the technical name of the field (the variable name) is the same to the string of the label, don't put string parameter for new API fields, because it's automatically taken`

2016-09-30 13:21 UTC, sudhir-serpentcs commented
Replaced old screenshots with new ones, removed string parameters from the fields.

2016-10-04 10:02 UTC, sudhir-serpentcs commented
Merged the PR of Astirpe.

2016-10-04 12:01 UTC, elicoidal requested changes

2016-10-04 12:01 UTC, elicoidal commented on business_requirement/README.rst
> +* `Six Sigma <(https://www.isixsigma.com/implementation/project-selection-tracking/business-requirements-document-high-level-review/>`_
remove "(" in URL

2016-10-21 12:16 UTC, astirpe commented
Code review :+1:

2016-10-21 14:45 UTC, elicoidal requested changes
small details. Other than that :+1:

2016-10-21 14:45 UTC, elicoidal commented on business_requirement/models/business_requirement.py
> +            ('stakeholder_approval', 'Stakeholder Approval'),
stakeholder_approved, Stakeholder Approved

2016-10-21 14:45 UTC, elicoidal commented on business_requirement/models/business_requirement.py
> +        self.state = 'stakeholder_approval'
modify here as well

2016-10-21 14:45 UTC, elicoidal commented on business_requirement/models/business_requirement.py
> +        if context.get(
formatting is a little bit weird but non blocking

2016-10-21 14:57 UTC, astirpe commented on business_requirement/models/business_requirement.py
> +            ('stakeholder_approval', 'Stakeholder Approval'),
@elicoidal in V8 the states values have `stakeholder_approval`, we should be careful when changing this item. It also implies to create migration scripts.

Maybe changing only the string 'Stakeholder Approved' would be enough?

2016-10-21 15:24 UTC, elicoidal commented on business_requirement/models/business_requirement.py
> +            ('stakeholder_approval', 'Stakeholder Approval'),
Agree. Let's just change the name

2016-10-21 15:44 UTC, astirpe commented on business_requirement/models/business_requirement.py
> +            ('stakeholder_approval', 'Stakeholder Approval'),
https://github.com/sudhir-serpentcs/business-requirement/pull/9

2016-10-21 15:46 UTC, astirpe commented on business_requirement/models/business_requirement.py
> +        self.state = 'stakeholder_approval'
Modification not required anymore, changing the name https://github.com/sudhir-serpentcs/business-requirement/pull/9 is enough

2016-12-02 16:44 UTC, dreispt commented
@moylop260 @elicoidal Are there still any blocking points?

2016-12-02 22:46 UTC, moylop260 approved these changes

2016-12-28 10:52 UTC, elicoidal commented
@dreispt sorry for the delay, just catching up.
I think this is safe to merge.

2016-12-28 10:52 UTC, merged