[ADD][10.0]BR001209-T24384: Business Requirement Gap Analysis Task
OCA/business-requirement pull request #268
Opened 2017-11-21 04:17 UTC by JoJoJoJoJoJoJo

Add gap analysis task in business view and a wizard to create the gap analysis task

2017-11-21 04:44 UTC, elicoidal requested changes
Thanks!
Mostly details.
No tests yet

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/README.rst
> +analysis and to allow you to find gap analysis task easily and create it
to find gap analysis task easily and create it automatically.
=> to create gap analysis task and easily find it

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/README.rst
> +<https://github.com/Elico-Corp/{project_repo}/issues>`_. In case of trouble, please
please adapt

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/README.rst
> +
I miss the runbot information

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/README.rst
> +* Odoo Community Association: `Icon <https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon.svg>`_.
use same icon as the other modules for business_requirements

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/README.rst
> +* Firstname Lastname <email.address@example.org>
Please adapt

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/README.rst
> +Maintainer
Use standard OCA template information

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/__manifest__.py
> +
remove empty lines

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/__manifest__.py
> +    'description': """
remove: only needed before v8

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/__manifest__.py
> +    'website': "https://www.elico-corp.com",
use the BR repo URL: https://github.com/OCA/business-requirement

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/views/business_requirement_gap_analysis_task.xml
> +    <data>
add copyright information in XML files too

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/views/business_requirement_gap_analysis_task.xml
> +                        Waning:changing master project
Waning:changing master project
=> Warning: changing master project

2017-11-21 04:44 UTC, elicoidal commented on business_requirement_gap_analysis_task/views/res_config.xml
> +    <data>
data tag is not necessary in v10

2017-11-21 07:58 UTC, JoJoJoJoJoJoJo commented
@elicoidal @seb-elico @lonlysun
changes done, review plz

2017-11-21 08:21 UTC, elicoidal requested changes
Almost there!
A good thing would to add demo data (one task link to one BR)

2017-11-21 08:22 UTC, elicoidal commented
@sysadminmatmoz @cubells Would you like to review this one?

2017-11-21 18:04 UTC, cubells requested changes
Minor changes.

Ready to approve.

2017-11-21 18:04 UTC, cubells commented on business_requirement_gap_analysis_task/__init__.py
> +from . import models
A blank line is needed after this

2017-11-21 18:04 UTC, cubells commented on business_requirement_gap_analysis_task/__manifest__.py
> +# © 2017 Elico Corp (https://www.elico-corp.com).
You must change `©` by Copyright

2017-11-21 18:04 UTC, cubells commented on business_requirement_gap_analysis_task/data/business_requirement_demo.xml
> +    <data noupdate="1">
It must be `odoo noupdate="1"`

2017-11-21 18:04 UTC, cubells commented on business_requirement_gap_analysis_task/data/gap_analysis_task_demo.xml
> +    <data noupdate="1">
Idem

2017-11-21 18:04 UTC, cubells commented on business_requirement_gap_analysis_task/models/business.py
> +                                   'you have to change it manually'
An `.` must end message

2017-11-21 18:04 UTC, cubells commented on business_requirement_gap_analysis_task/wizard/create_gap_task.xml
> +</odoo>
an end blank line is neeed

2017-11-21 18:04 UTC, cubells commented on business_requirement_gap_analysis_task/wizard/create_gap_task.xml
> +                or
`or` is not needed by usability

2017-11-22 00:32 UTC, elicoidal commented
@cubells thanks for the review!

2017-11-22 07:28 UTC, JoJoJoJoJoJoJo commented
@cubells 
Thanks for the review!
changes are made, review the pr plz.
cc @elicoidal  @seb-elico  @lonelysun

2017-11-22 09:01 UTC, elicoidal approved these changes

2017-11-27 03:09 UTC, lonelysun requested changes
Change the field name and don't forget the reference section

2017-11-27 03:09 UTC, lonelysun commented on business_requirement_gap_analysis_task/models/business.py
> +    gap_analysis_task = fields.Many2one(
change field name to gap_analysis_task_id, The fields of the many2one type end with _id

2017-11-27 03:09 UTC, lonelysun commented on business_requirement_gap_analysis_task/models/res_config.py
> +    gap_task_category = fields.Many2one(
change field name to gap_analysis_task_id, The fields of the many2one type end with _id

2017-11-27 09:47 UTC, elicoidal commented
@JoJoJoJoJoJoJo Can you attend @lonelysun comments?
@cubells Can you please review the changes?

2017-11-27 10:48 UTC, JoJoJoJoJoJoJo commented
Done @lonelysun
cc @elicoidal

2017-11-28 12:20 UTC, cubells requested changes
Minor changes.

2017-11-28 12:20 UTC, cubells commented on business_requirement_gap_analysis_task/data/business_requirement_demo.xml
> +    <data>
Tag `data` is not needed here. Remove.

2017-11-28 12:20 UTC, cubells commented on business_requirement_gap_analysis_task/data/gap_analysis_task_demo.xml
> +    <data>
Tag `data` is not needed here. Remove.

2017-11-28 12:20 UTC, cubells commented on business_requirement_gap_analysis_task/models/business.py
> +            if rec.gap_analysis_task_id:
You can improve these lines with this one:
`if self.mapped('rec.gap_analysis_task_id'):`

2017-11-28 16:29 UTC, cubells commented on business_requirement_gap_analysis_task/models/business.py
> +            if rec.gap_analysis_task_id:
better:

`for rec in self.mapped('rec.gap_analysis_task_id'):`

2017-11-29 03:46 UTC, lonelysun approved these changes

2017-11-29 04:45 UTC, elicoidal commented
@cubells Please review again the corrections

2017-11-30 19:31 UTC, cubells approved these changes
LGTM

code review and test.

Goog job @JoJoJoJoJoJoJo

2017-12-01 00:20 UTC, elicoidal commented
Thanks @cubells

2017-12-01 00:21 UTC, merged