[ADD]business_requirement_versioning module
OCA/business-requirement pull request #279
Opened 2018-03-21 08:33 UTC by lonelysun

replace #270

2018-03-22 11:25 UTC, elicoidal commented
@gurneyalex I rebuilt the runbot but can get it up: https://runbot.odoo-community.org/runbot/build/3313645
Could you help?

2018-03-27 04:42 UTC, elicoidal commented
@lonelysun I have a traceback in Runbot (http://3320993-270-68c6d0.runbot1.odoo-community.org/web):
1. Go to BR0006, Set as Approved
2. Click on Renew
3. Get the following:
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 895, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 883, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/business-requirement/business_requirement_versioning/models/business_requirement_versioning.py", line 81, in renew_br
    version=count
  File "/home/odoo/build/OCA/business-requirement/business_requirement_versioning/models/business_requirement_versioning.py", line 53, in copy
    return super(BusinessRequirementVersion, self).copy(vals)
  File "/home/odoo/odoo-10.0/addons/pad/models/pad.py", line 132, in copy
    return super(PadCommon, self).copy(default)
  File "/.repo_requirements/odoo/odoo/models.py", line 4403, in copy
    vals = self.copy_data(default)[0]
  File "/home/odoo/odoo-10.0/addons/mail/models/mail_thread.py", line 299, in copy_data
    return super(MailThread, self.with_context(mail_notrack=True)).copy_data(default=default)
  File "/.repo_requirements/odoo/odoo/models.py", line 4324, in copy_data
    lines = [rec.copy_data()[0] for rec in self[name].sorted(key='id')]
TypeError: 'NoneType' object has no attribute '__getitem__'

2018-09-03 23:44 UTC, elicoidal requested changes

2018-09-03 23:44 UTC, elicoidal commented on business_requirement_versioning/__manifest__.py
> +    'data': [
Missing demo data (one example is enough)

2018-09-03 23:44 UTC, elicoidal commented on business_requirement_versioning/models/business_requirement_versioning.py
> +        res.append(('renewed', 'Renewed'))
renewed -> updated

2018-09-03 23:44 UTC, elicoidal commented on business_requirement_versioning/tests/__init__.py
> +from . import test_renew
renew->update

2018-09-03 23:44 UTC, elicoidal commented on business_requirement_versioning/views/button_view.xml
> +                <button string="Renew" name="renew_br"
Renew -> update (everywhere)

2018-09-13 01:28 UTC, elicoidal commented
@lonelysun please have a look

2018-09-18 18:34 UTC, nikul-serpentcs commented on business_requirement_versioning/__manifest__.py
> +    'website': 'https://www.elico-corp.com/',
@lonelysun IMHO change URL as per [this](https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L10)

2018-09-18 18:37 UTC, nikul-serpentcs commented on business_requirement_versioning/views/button_view.xml
> +            <xpath expr="//header/field[@name='state']" position="before">
@lonelysun IMO Directly use `<field name="state" position="before">`

2018-09-18 18:39 UTC, nikul-serpentcs commented on business_requirement_versioning/models/business_requirement_versioning.py
> +            count = len(record.env['business.requirement'].search(
@lonelysun IMO here use `search_count` method,  So Directly use count.

2018-09-21 08:55 UTC, elicoidal commented
@lonelysun Let me know if you can finish this

2019-03-15 09:31 UTC, elicoidal commented
@ruter-lyu can you finish this one too and port it to v12?

2019-03-15 10:12 UTC, ruter-lyu commented
> @ruter-lyu can you finish this one too and port it to v12?

When I finished other migrations I'll start to do this

2019-07-23 17:54 UTC, pedrobaeza commented
Closing by inactivity

2019-07-23 17:54 UTC, closed without merging