[MIG] migrate business_requirement_deliverable_crm from 10.0 to 12.0
OCA/business-requirement pull request #299
Opened 2019-03-20 10:03 UTC by ruter-lyu

@elicoidal

2019-03-21 01:12 UTC, elicoidal requested changes
Please take into account #300 and refactor the module.

2019-03-21 01:12 UTC, elicoidal commented on business_requirement_deliverable_crm/models/crm.py
> +    resource_cost_total = fields.Float(
should be deliverable not resource
(might require migration script though)

2019-03-21 01:12 UTC, elicoidal commented on business_requirement_deliverable_crm/models/crm.py
> +    def _compute_resource_cost_total(self):
deliverable

2019-03-21 01:12 UTC, elicoidal commented on business_requirement_deliverable_crm/views/crm_view.xml
> +            <xpath expr="//button[@name='action_set_won_rainbowman']" position='before'>
improve readability of XML

2019-03-21 01:12 UTC, elicoidal commented on business_requirement_deliverable_crm/wizard/crm_make_sale.py
> +    def make_order(self):
You might need to refactor this one to be able to fit to #300 
We should be able to generate a SQ either from Opp (based onlist of BR in the linked project) or based on the list of selected BR(s)

2019-03-29 06:28 UTC, JoJoJoJoJoJoJo approved these changes
Technically LGTM

2019-03-29 06:28 UTC, JoJoJoJoJoJoJo commented on business_requirement_deliverable_crm/models/crm.py
> +            [br.total_revenue for br in
No need to transfer to list.

2019-03-29 06:28 UTC, JoJoJoJoJoJoJo commented on business_requirement_deliverable_crm/tests/test_wizard_br.py
> +        try:
There shouldn't be try..catch in UT.

2021-11-13 17:28 UTC, pedrobaeza commented
Closing as old and not green

2021-11-13 17:28 UTC, closed without merging