[ADD] Migrated business_requirement_deliverable_cost module from v8 to v9
OCA/business-requirement pull request #30
Opened 2016-09-30 08:23 UTC by sudhir-serpentcs

WIP until #25  and #26  is merged
---------------------------------

Migrated business_requirement_deliverable_default module from v8 to v9.
WIP: Clean up of unit test cases.
@dreispt @pedrobaeza @jbeficent @moylop260 Please review.

2016-09-30 16:23 UTC, elicoidal requested changes
:+1: 
I will update the README in separate file

2016-09-30 16:23 UTC, elicoidal commented on business_requirement_deliverable_cost/README.rst
> +This module is part of a set of modules (`Business Requirements <https://github.com/OCA/business-requirement/blob/8.0/README.md>`_)
9.0

2016-10-04 12:03 UTC, elicoidal approved these changes
:+1: 
Small details
@pedrobaeza @moylop260 @mmalorni

2016-10-04 12:03 UTC, elicoidal commented on business_requirement_deliverable_cost/__openerp__.py
> +        'static/description/icon.png',
add icon image

2017-02-09 13:16 UTC, sudhir-serpentcs commented
Rebased the PR.
@dreispt @pedrobaeza @jbeficent @moylop260 @elicoidal

2017-02-14 13:36 UTC, astirpe requested changes

2017-02-14 13:36 UTC, astirpe commented on business_requirement_deliverable_cost/models/business.py
> +        if br_deliverable and br_deliverable.business_requirement_id:
Please apply the same fix that was made for V8 in https://github.com/OCA/business-requirement/pull/66/files

2017-02-24 07:23 UTC, elicoidal commented on business_requirement_deliverable_cost/models/business.py
> +        if br_deliverable and br_deliverable.business_requirement_id:
@sudhir-serpentcs Can you attend @astirpe recommendation so that we can merge cleanly?

2017-02-27 09:13 UTC, sudhir-serpentcs commented on business_requirement_deliverable_cost/models/business.py
> +        if br_deliverable and br_deliverable.business_requirement_id:
@astirpe @elicoidal Done

2017-03-08 01:32 UTC, elicoidal commented
@astirpe @sudhir-serpentcs can we merge this one?

2017-03-08 07:04 UTC, sudhir-serpentcs commented
I think yes. We can merge it.
@elicoidal

2017-03-08 08:01 UTC, astirpe commented
With commit 6ebfc4b2c83be6272f611720cf3f18af1daf46f8 the method `def _get_partner()` was replaced with a related field `partner_id`. Is it possible to apply the same change before to merge? Otherwise we merge now and then open a new PR for that. I think doing now is the quickest way. What do you think?

2017-03-08 09:54 UTC, elicoidal commented
agree with @astirpe indeed.
@sudhir-serpentcs could you do that and then we move forward?

2017-03-10 10:13 UTC, sudhir-serpentcs commented
`With commit 6ebfc4b the method def _get_partner() was replaced with a related field partner_id. Is it possible to apply the same change before to merge? Otherwise we merge now and then open a new PR for that. I think doing now is the quickest way. What do you think?`

@elicoidal @astirpe Replaced the _get_partner() method by related partner_id field.

2017-03-11 01:14 UTC, elicoidal requested changes
small details then we can move forward

2017-03-11 01:14 UTC, elicoidal commented on business_requirement_deliverable_cost/models/business.py
> +#    @api.multi
please remove dead codes

2017-03-11 01:14 UTC, elicoidal commented on business_requirement_deliverable_cost/security/business_requirement_deliverable_security.xml
> +            <field name="implied_ids" eval="[(4, ref('business_requirement.group_business_requirement_user'))]"/>
Can you improve the format of the lines for readibility?

2017-03-11 15:23 UTC, astirpe approved these changes
For me is OK to merge, after the removal of dead code ...

2017-03-15 06:28 UTC, sudhir-serpentcs commented
@elicoidal @astirpe Removed dead code and improved security xml.

2017-03-15 07:33 UTC, elicoidal approved these changes

2017-03-15 07:33 UTC, merged