[MIG] migrate business_requirement_deliverable_resource_template from 10.0 to 12.0
OCA/business-requirement pull request #304
Opened 2019-03-22 03:48 UTC by ruter-lyu

2019-03-25 01:22 UTC, elicoidal reviewed
LGTM. Please prepare the  README

2019-03-25 01:22 UTC, elicoidal commented
@JoJoJoJoJoJoJo @joycehuan @seb-elico please have a look

2019-03-29 06:58 UTC, JoJoJoJoJoJoJo reviewed
Some improvement.

2019-03-29 06:58 UTC, JoJoJoJoJoJoJo commented on business_requirement_deliverable_resource_template/README.rst
> +Business Requirement
Change the name to module name.

2019-03-29 06:58 UTC, JoJoJoJoJoJoJo commented on business_requirement_deliverable_resource_template/models/business_requirement_resource_template.py
> +        return [(0, 0, item) for index, item in enumerate(data)]
```suggestion
        return [(0, 0, item) for item in data]
```

2019-03-29 09:12 UTC, nikul-serpentcs requested changes
netpicking

2019-03-29 09:12 UTC, nikul-serpentcs commented on business_requirement_deliverable_resource_template/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/222/10.0
@ruter-lyu 10.0/12.0

2019-03-29 09:12 UTC, nikul-serpentcs commented on business_requirement_deliverable_resource_template/README.rst
> +   :alt: License: AGPL-3
@ruter-lyu LGPL-3.0

2021-11-13 17:29 UTC, pedrobaeza commented
Closing as old and not green

2021-11-13 17:29 UTC, closed without merging