[MIG] migrate business_requirement_deliverable_project from 10.0 to 12.0
OCA/business-requirement pull request #305
Opened 2019-03-22 03:49 UTC by ruter-lyu

2019-03-25 00:45 UTC, elicoidal reviewed
Almost there. Can you prepare the README too and I will review it

2019-03-25 00:45 UTC, elicoidal commented on business_requirement_deliverable_project/__manifest__.py
> +        'project_parent'
You probably have to think about migrating this one.

2019-03-25 00:45 UTC, elicoidal commented on business_requirement_deliverable_project/models/project.py
> +            if br.state not in ['stakeholder_approval', 'cancel', 'done']:
I am not sure about this constraint anymore cc @seb-elico

2019-03-25 01:17 UTC, elicoidal commented
@JoJoJoJoJoJoJo @joycehuan @seb-elico please have a look

2019-03-29 07:22 UTC, JoJoJoJoJoJoJo approved these changes
LGTM

2019-03-29 07:22 UTC, JoJoJoJoJoJoJo commented on business_requirement_deliverable_project/models/business.py
> +    all_project_generated = fields.Boolean(
Move the field up for convenience.

2019-03-29 09:24 UTC, nikul-serpentcs requested changes
Improve code

2019-03-29 09:24 UTC, nikul-serpentcs commented on business_requirement_deliverable_project/README.rst
> +   :alt: License: AGPL-3
LGPL-3

2019-03-29 09:24 UTC, nikul-serpentcs commented on business_requirement_deliverable_project/README.rst
> +This module is part of a set of modules (`Business Requirements <https://github.com/OCA/business-requirement/blob/10.0/README.md>`_)
10.0 --> 12.0

2019-03-29 09:24 UTC, nikul-serpentcs commented on business_requirement_deliverable_project/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/222/10.0
same herer

2019-03-29 09:24 UTC, nikul-serpentcs commented on business_requirement_deliverable_project/wizard/generate_projects_view.xml
> +                <button string="_Cancel" class="oe_link" special="cancel"/>
string="Cancel"

2019-03-29 09:24 UTC, nikul-serpentcs commented on business_requirement_deliverable_project/wizard/generate_projects_view.xml
> +                <button name="apply" string="_Apply" type="object"
string="Apply"

2019-03-29 09:24 UTC, nikul-serpentcs commented on business_requirement_deliverable_project/views/business_view.xml
> +            <xpath expr="//form/sheet/div[@name='button_box']"
`//div[@name='button_box']` is enough for xpath

2021-11-13 17:29 UTC, pedrobaeza commented
Closing as old and not green

2021-11-13 17:29 UTC, closed without merging