[MIG] migrate business_requirement_etherpad from 10.0 to 12.0
OCA/business-requirement pull request #306
Opened 2019-03-22 03:50 UTC by ruter-lyu

2019-03-25 01:30 UTC, elicoidal reviewed
LGTM
Please update the README

2019-03-29 07:31 UTC, JoJoJoJoJoJoJo approved these changes
LGTM

2019-03-29 09:19 UTC, nikul-serpentcs requested changes
netpicking

2019-03-29 09:19 UTC, nikul-serpentcs commented on business_requirement_etherpad/README.rst
> +   :alt: License: AGPL-3
@ruter-lyu LGPL-3

2019-03-29 09:19 UTC, nikul-serpentcs commented on business_requirement_etherpad/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/222/10.0
10 --> 12

2021-11-13 17:29 UTC, pedrobaeza commented
Closing as old and not green

2021-11-13 17:29 UTC, closed without merging