[FIX][8.0] Transfer Fiscal Position when creating a quotation
OCA/business-requirement pull request #51
Opened 2016-10-13 13:42 UTC by astirpe

Fixes #44

2016-10-14 14:19 UTC, elicoidal commented
@astirpe thanks for your contribution.
:+1: 
@mmalorni

2016-10-14 14:23 UTC, pedrobaeza requested changes

2016-10-14 14:23 UTC, pedrobaeza commented on business_requirement_deliverable_crm/wizard/crm_make_sale.py
> +                    'tax_id': [(6, 0, [x.id for x in taxes])],
Use directly `taxes.ids`

2016-10-14 14:23 UTC, pedrobaeza commented on business_requirement_deliverable_crm/wizard/crm_make_sale.py
> +                    taxes = fp.map_tax(taxes)
Filter per company: `fp.map_tax(taxes).filtered(lambda x: x.company_id == ...`

2016-10-14 14:23 UTC, pedrobaeza commented
Anyway, why don't execute onchanges programatically to avoid all this manual stuff?

2016-10-14 14:37 UTC, elicoidal commented
> Anyway, why don't execute onchanges programatically to avoid all this manual stuff?

Good point indeed

2016-10-14 16:31 UTC, pedrobaeza approved these changes

2016-10-14 16:36 UTC, astirpe commented
Regarding the proposal of @pedrobaeza to make use of onchange methods, I would propose a new PR (as enhancement) to partially rewrite the code of this module

2016-10-14 16:37 UTC, pedrobaeza commented
OK, I agree. It's out of the scope of this PR

2016-10-17 11:02 UTC, elicoidal commented
OK with that too

2016-10-17 12:16 UTC, pedrobaeza commented
Merging then

2016-10-17 12:16 UTC, merged

2016-10-18 03:49 UTC, elicoidal commented
thanks @pedrobaeza @astirpe