[IMP] business_requirement_deliverable_cost:
OCA/business-requirement pull request #62
Opened 2016-12-28 03:17 UTC by victormartinelicocorp

Add the pricelist calculation with preference from the master project.
	modified:   business_requirement_deliverable_cost/models/__init__.py
	modified:   business_requirement_deliverable_cost/models/business.py
	new file:   business_requirement_deliverable_cost/models/project.py

2016-12-28 03:23 UTC, seb-elico requested changes

2016-12-28 03:23 UTC, seb-elico commented on business_requirement_deliverable_cost/models/business.py
> +        else:
No need for `else`

2016-12-28 03:23 UTC, seb-elico commented on business_requirement_deliverable_cost/models/business.py
> +        if br_deliverable.business_requirement_id.id:
Shouldn't this line be under the previous `if`?

2016-12-28 03:23 UTC, seb-elico commented on business_requirement_deliverable_cost/models/business.py
> +        if project_id:
Why not using `if project_id and project_id.pricelist_id:` (also applies for the `if` below)?

2016-12-28 03:39 UTC, victormartinelicocorp commented
@seb-elico Please have a check

2016-12-28 03:42 UTC, seb-elico requested changes

2016-12-28 03:42 UTC, seb-elico commented on business_requirement_deliverable_cost/models/business.py
> +        br_id = br_deliverable = False
Since those variables are only used inside the `if`s, I think there's no need to init them here

2016-12-28 03:42 UTC, seb-elico commented on business_requirement_deliverable_cost/models/business.py
> +            return partner_id.property_product_pricelist
Shouldn't we have `return False` at the end of the function?

2016-12-28 03:48 UTC, victormartinelicocorp commented
@seb-elico done

2016-12-28 03:50 UTC, seb-elico approved these changes

2016-12-28 03:54 UTC, seb-elico commented
@victormartinelicocorp Just one question: I thought that when there's no estimation pricelist defined in the project and also no pricelist defined on the customer/partner, then we would use the default pricelist of the company. Why this last one (default pricelist of the company) is not in the function `_get_pricelist`?

2016-12-28 04:33 UTC, victormartinelicocorp commented
> @victormartinelicocorp Just one question: I thought that when there's no estimation pricelist defined in the project and also no pricelist defined on the customer/partner, then we would use the default pricelist of the company. Why this last one (default pricelist of the company) is not in the function _get_pricelist?

@seb-elico I've checked this and if I understand well your concern. Odoo by default prevent to manage a pricelist different from parent company so if exist is always the company parent one and it's unique.

2016-12-28 04:59 UTC, seb-elico commented
@victormartinelicocorp ok clear!
This PR LGTM :+1:

2017-02-24 08:03 UTC, elicoidal commented
@victormartinelicocorp Can you resolve conflicts?

2017-02-24 10:18 UTC, victormartinelicocorp commented
> @victormartinelicocorp Can you resolve conflicts?

@elicoidal done

2017-02-24 10:33 UTC, elicoidal approved these changes

2017-02-24 10:34 UTC, elicoidal commented
@seb-elico

2017-02-24 12:25 UTC, andhit-r approved these changes
:+1:

2017-02-25 11:05 UTC, elicoidal commented
thanks  @andhit-r 
By the way, you might want to use the GH approval process as well.

2017-02-25 11:06 UTC, merged

2017-02-25 11:24 UTC, andhit-r commented
@elicoidal your welcome. GH == GitHub? I did use it for approved this PR.

2017-02-25 13:38 UTC, elicoidal commented
Yes GH=github :p 
:o I didnot notice it (facepalm). I just saw the :+1: