Update README.md
OCA/business-requirement pull request #74
Opened 2017-02-25 12:59 UTC by elicoidal

Added Badges
Added introduction

2017-02-25 13:02 UTC, elicoidal commented
I am not sure about coverall and how to get the list of addons updated in the README

2017-02-26 16:53 UTC, pedrobaeza commented
Coveralls is not used anymore. Use Codecov badge.

2017-02-27 07:29 UTC, elicoidal commented
@pedrobaeza

2017-02-27 11:03 UTC, astirpe commented
👍

2017-02-27 11:36 UTC, astirpe requested changes

2017-02-27 11:36 UTC, astirpe commented on README.md
> +[![codecov](https://codecov.io/gh/OCA/business-requirement/branch/10.0/graph/badge.svg)](https://codecov.io/gh/OCA/project)
Must be `business-requirement` instead of `project` . Please check

2017-02-27 12:16 UTC, elicoidal commented
@astirpe

2017-02-27 12:18 UTC, astirpe approved these changes

2017-03-05 13:36 UTC, sbidoul requested changes
The addons placeholder is incorrect, see example in #75

2017-03-10 15:07 UTC, dreispt approved these changes
To squash merge

2017-03-11 00:55 UTC, merged